export enum EnumFmDate {
    YEAR_MONTH_DAY_JP = "YYYY年MM月DD日",
    YEAR_MONTH_DAY_NORMAL = "YYYY/MM/DD",
    YEAR_MONTH_DAY_NORMAL_DASH = "YYYY-MM-DD",
    YEAR_DAY_MONTH_NORMAL_DASH = "YYYY-DD-MM",
    YEAR_MONTH_DAY_HMS_JP = "YYYY年MM月DD日 HH:mm:ss",
    YEAR_MONTH_DAY_HMS_NORMAL = "YYYY/MM/DD HH:mm:ss",
    YEAR_MONTH_DAY_HM_JP = "YYYY年MM月DD日 HH:mm",
    YEAR_MONTH_DAY_HM_NORMAL = "YYYY/MM/DD HH:mm",
    YEAR_MONTH_DAY_HM_DASH = "YYYY-MM-DD HH:mm",
    DATE_API_CREATE = "YYYY-MM-DDT00:00:00.000Z",
    DAY_MONTH_YEAR_NORMAL = "DD/MM/YYYY",
    DAY_MONTH_YEAR_NORMAL_DASH = "DD-MM-YYYY",
}
