###############################################################################
# Region SES
ses.region: "us-west-2"

# Mail
ja.mail.subject: "[insightwatch]セキュリティチェック結果通知（{{project_name}}）"
en.mail.subject: "[insightwatch]Security check result notification （{{project_name}}）"
en.mail.body.text.filepath: "check/notify/mail/cis_checkresult_template_en.tpl"
ja.mail.body.text.filepath: "check/notify/mail/cis_checkresult_template_ja.tpl"
mail.from: "sys@insightwatch.io"

# Slack
ja.slack.username: "insightwatch"
en.slack.username: "insightwatch"
slack.iconurl: "https://insightwatch.io/app/assets/images/iw_em_color_slack_file.png"
ja.slack.message.filepath: "check/notify/mail/checkresult_slack_template_ja.tpl"
en.slack.message.filepath: "check/notify/mail/checkresult_slack_template_en.tpl"

# Unregistered User invite Mail
ja.invite_mail.insightwatch.subject: "[insightwatch]へ招待されました"
ja.invite_mail.insightwatch.body.text.filepath: "check/notify/mail/insightwatch_user_invite_template_ja.tpl"
en.invite_mail.insightwatch.subject: "You're Invited: insightwatch"
en.invite_mail.insightwatch.body.text.filepath: "check/notify/mail/insightwatch_user_invite_template_en.tpl"
invite_mail.insightwatch.from: "sys@insightwatch.io"

ja.invite_mail.opswitch.subject: "[opswitch]へ招待されました"
ja.invite_mail.opswitch.body.text.filepath: "check/notify/mail/opswitch_user_invite_template_ja.tpl"
en.invite_mail.opswitch.subject: "You're Invited: opswitch"
en.invite_mail.opswitch.body.text.filepath: "check/notify/mail/opswitch_user_invite_template_en.tpl"
invite_mail.opswitch.from: "sys@opswitch.io"

# Mail error execute check
ja.checkerror_notice_mail.subject: "[insightwatch]セキュリティチェック処理でエラーが発生しました。（{{project_name}}）"
en.checkerror_notice_mail.subject: "[insightwatch]Security check error alert（{{project_name}}）"
en.checkerror_notice_mail.body.text.filepath: "check/notify/mail/notice_error_execute_check_en.tpl"
ja.checkerror_notice_mail.body.text.filepath: "check/notify/mail/notice_error_execute_check_ja.tpl"
en.message_notice_error_execute_check_security.filepath: "check/notify/mail/message_notice_error_execute_check_security_en.yaml"
ja.message_notice_error_execute_check_security.filepath: "check/notify/mail/message_notice_error_execute_check_security_ja.yaml"

# Config apply change mail
en.mail.insightwatch.subject: "insightwatch Confirm your change e-mail address"
en.mail.insightwatch.body.text.filepath: "check/notify/mail/insightwatch_apply_change_mail_template_en.tpl"
ja.mail.insightwatch.subject: "insightwatch メールアドレス変更確認"
ja.mail.insightwatch.body.text.filepath: "check/notify/mail/insightwatch_apply_change_mail_template_ja.tpl"
mail.insightwatch.from: "sys@insightwatch.io"
en.mail.opswitch.subject: "opswitch Confirm your change e-mail address"
en.mail.opswitch.body.text.filepath: "check/notify/mail/opswitch_apply_change_mail_template_en.tpl"
ja.mail.opswitch.subject: "opswitch メールアドレス変更確認"
ja.mail.opswitch.body.text.filepath: "check/notify/mail/opswitch_apply_change_mail_template_ja.tpl"
mail.opswitch.from: "sys@opswitch.io"

# Config response execute change mail
mail.insightwatch.response.complete: '<html><head><meta http-equiv="refresh" content="0; URL=/app/#/emailchangecomplete.html" /></head></html>'
mail.insightwatch.response.error: '<html><head><meta http-equiv="refresh" content="0; URL=/app/error.html" /></head></html>'
mail.opswitch.response.complete: '<html><head><meta http-equiv="refresh" content="0; URL=https://app.opswitch.io/emailchangecomplete" /></head></html>'
mail.opswitch.response.error: '<html><head><meta http-equiv="refresh" content="0; URL=https://app.opswitch.io/emailchangeerror" /></head></html>'
