# ===================================================================
# Redis server config
# ===================================================================

singleServerConfig:
  address: "redis://${REDIS_HOST:-127.0.0.1:6379}"