@startuml{メールアドレス変更画面.png}
title [メールアドレス変更画面]
hide footbox

actor ユーザー as user
boundary メールアドレス変更画面 as view_1
boundary メールアドレス変更確認画面 as view_2
database ユーザープール as user_pools <<cognito>> #purple

== 表示 ==
user -> view_1 :画面表示
activate view_1
    view_1 -> view_1 :画面描画
    view_1 --> user
deactivate view_1

== メールアドレス変更 ==
note over user, user_pools #pink :メールアドレス変更可否、手順は要確認
user -> view_1 :メールアドレス変更
activate view_1
    view_1 -> view_1 :バリデーションチェック
    view_1 -> user_pools :メールアドレス変更
    note right :メールアドレスを変更し、確認コードを載せたメールを送信する
    user_pools --> view_1
    note over user_pools #pink :キャンセル方法要確認
    view_1 -> view_2 :表示
deactivate view_1

@enduml
