export const listProductTradingDUMMY =
{
  "productTradingsByProgress": [
    {
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress6\", \"zh_cn\": \"\"}",
      "productTradings": [
        {
          "productTradingId": 61,
          "customerName": null,
          "customerId": 21,
          "productId": 86,
          "productName": "商品A100",
          "quantity": 9,
          "price": 1888,
          "amount": 16992,
          "productTradingProgressId": 1,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress6\", \"zh_cn\": \"\"}",
          "progressOrder": 1,
          "isAvailable": true,
          "endPlanDate": "2020-07-14T00:00:00Z",
          "orderPlanDate": "2020-07-15T00:00:00Z",
          "memo": "RRRRR",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1218,
            "amount": 16992,
            "contentChange": null,
            "endPlanDate": "2020-07-14T00:00:00Z",
            "memo": "RRRRR",
            "orderPlanDate": "2020-07-15T00:00:00Z",
            "productTradingId": 61,
            "productId": 86,
            "price": 1888,
            "productTradingProgressId": 1,
            "productTradingData": "{}",
            "quantity": 9,
            "activityId": 172,
            "createdDate": "2020-07-31T13:20:53.808582Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T13:20:53.808582Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T13:20:53.808582Z",
          "updatedDate": "2020-07-31T13:20:53.808582Z"
        }
      ],
      "total": 1
    },
    {
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress1\", \"zh_cn\": \"\"}",
      "productTradings": [
        {
          "productTradingId": 60,
          "customerName": null,
          "customerId": 21,
          "productId": 113,
          "productName": "商品A",
          "quantity": 10,
          "price": 100,
          "amount": 1000,
          "productTradingProgressId": 2,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress1\", \"zh_cn\": \"\"}",
          "progressOrder": 2,
          "isAvailable": true,
          "endPlanDate": "2020-07-07T00:00:00Z",
          "orderPlanDate": "2020-07-02T00:00:00Z",
          "memo": "メモ商品",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1217,
            "amount": 1000,
            "contentChange": null,
            "endPlanDate": "2020-07-07T00:00:00Z",
            "memo": "メモ商品",
            "orderPlanDate": "2020-07-02T00:00:00Z",
            "productTradingId": 60,
            "productId": 113,
            "price": 100,
            "productTradingProgressId": 2,
            "productTradingData": "{}",
            "quantity": 10,
            "activityId": 172,
            "createdDate": "2020-07-31T13:20:53.808582Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T13:20:53.808582Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T13:20:53.808582Z",
          "updatedDate": "2020-07-31T13:20:53.808582Z"
        },
        {
          "productTradingId": 58,
          "customerName": null,
          "customerId": 18,
          "productId": 86,
          "productName": "商品A100",
          "quantity": 111,
          "price": 700,
          "amount": 77700,
          "productTradingProgressId": 2,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress1\", \"zh_cn\": \"\"}",
          "progressOrder": 2,
          "isAvailable": true,
          "endPlanDate": "2020-07-15T00:00:00Z",
          "orderPlanDate": "2020-07-10T00:00:00Z",
          "memo": "MEMoX",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1207,
            "amount": 77700,
            "contentChange": null,
            "endPlanDate": "2020-07-15T00:00:00Z",
            "memo": "MEMoX",
            "orderPlanDate": "2020-07-10T00:00:00Z",
            "productTradingId": 58,
            "productId": 86,
            "price": 700,
            "productTradingProgressId": 2,
            "productTradingData": "{}",
            "quantity": 111,
            "activityId": 171,
            "createdDate": "2020-07-31T12:33:25.144582Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T12:33:25.144582Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T12:33:25.144582Z",
          "updatedDate": "2020-07-31T12:33:25.144582Z"
        },
        {
          "productTradingId": 67,
          "customerName": null,
          "customerId": 19,
          "productId": 51,
          "productName": "セット商品2",
          "quantity": 11,
          "price": 111,
          "amount": 1221,
          "productTradingProgressId": 2,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress1\", \"zh_cn\": \"\"}",
          "progressOrder": 2,
          "isAvailable": true,
          "endPlanDate": "2020-07-22T00:00:00Z",
          "orderPlanDate": "2020-07-03T00:00:00Z",
          "memo": "memo",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1224,
            "amount": 1221,
            "contentChange": null,
            "endPlanDate": "2020-07-22T00:00:00Z",
            "memo": "memo",
            "orderPlanDate": "2020-07-03T00:00:00Z",
            "productTradingId": 67,
            "productId": 51,
            "price": 111,
            "productTradingProgressId": 2,
            "productTradingData": "{}",
            "quantity": 11,
            "activityId": 174,
            "createdDate": "2020-07-31T13:28:51.061925Z",
            "createdUser": 10022,
            "updatedDate": "2020-07-31T13:28:51.061925Z",
            "updatedUser": 10022
          },
          "employee": {
            "employeeId": 10022,
            "employeeName": null,
            "employeeSurname": "Phuong BV",
            "photoFilePath": "https://ms2-dev-files.s3.ap-northeast-1.amazonaws.com/tenants/mercyrrczkni/service_data/employee/10002_lemon_20200731124037638.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkYwRAIgMuyZ5mGzYWnzBYo9EmXZxKhd2qECfhLZQ7wqCWxq0JsCIAXOvxIxDFJPk1GdPIqp5JaDOMfQeefb3Pyu7E1yOsLjKvcDCFIQABoMMDA4MDc2MzYzNTE2Igyg7zKFUicnsOu76Rwq1AO9CJd8yFbubAzg2BLp3JPPBSh1Vo5A8FKRg7xEAqoHouJ%2Be8%2BRLQcIW2PXKR8GsRKMLWi2sH5aMp79tMqTMDkrBUgcg9EqMxQWIdpBRgezwLxn%2FleaC%2BRpgbL%2Bi9PmxN2kzKSVbUf7FdfwIu51yIoHGR8dBPz7AVqSZ5Kd06IoarHhpWMdKv8OZt%2Fz4vR2kpVzdRIw8ItBZ97LL6yuUR9WASZxdpW3Jalgq0z1s%2BYUal8%2FNTky%2Bw1MA%2BOP5A8%2BM3%2FqcB4nS5Sx6IVLZ9MHPvJXy4UlsP8f8eUuEN8CsfiOwJgQYG8QXibHPVNr8aHmOFQDa5VRD5neTDtyRUWIc44P2k%2FIL4aBaJuYMtgHd2G3fVRcuAyF%2BOQOQevJKZmaxkWPHT7HLKv6%2FPTVDaR7d4DJsfSV1YBQ0dpymHNQKY%2FFkPy8CKkJB4FUfCWfcl2UO3CQ0jEL2rzNgeFaK00afZqex10bYfODv%2BTlrIxjreb7myEat1DMtWL%2F9T18LmfI74r8A2nsUh1bS0DkDoJDmMimY3l5yIcjAXIAK7C4FwEPSdIegdXyWb05t8iB9yWnSkZZiVl1X2JwxH1ul2eQCkwEGsgQ6zjBd5UtjaOH21LgIRh0%2Fu8w%2BfGS%2BQU68AHF6%2Fum2%2BgCIHVlKOCmy9vq0diXepGvhBtF%2ByvRfxlctkedZH5SU4Rd7bgwmhSayi%2BoYBoRL4jSog4rUQGQDJizwQvw%2FfZRSjbf5fWxeWEulY0IqsOLx2m5n6wWlUmtBb6wlQ7O12MwguAIIORhoQRIAglAkTD7w4m0c7JIMYWBFfgNdETNlyhfjywYlD4o9T9IorPr5RVRnc%2BnqdzcIivqN1tNVQ37wTWab3CNFxNaUL5aAfw88PwKbkKoLYZ1ES9VrtTEYejAc3kqE3sx1ZjORW0IY3sQG2Qcc1A7n8sN49hguznL5A6zdJ0djUXHqUU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200801T023000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=9999&X-Amz-Credential=ASIAQDYLDQ36DH74BQ7K%2F20200801%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=0565fe4a363e9cf195dbff94ea835dfc7a7bc9de5d687080f7b0c420d9807fa2",
            "departmentName": "HaiTD",
            "positionName": null,
            "employeeSurnameKana": "PhuongBV",
            "employeeNameKana": null,
            "cellphoneNumber": "",
            "telephoneNumber": "",
            "email": "buivanphuong@luvina.net"
          },
          "createdUser": {
            "employeeId": 10022,
            "employeeName": null,
            "employeeSurname": "Phuong BV",
            "photoFilePath": "https://ms2-dev-files.s3.ap-northeast-1.amazonaws.com/tenants/mercyrrczkni/service_data/employee/10002_lemon_20200731124037638.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkYwRAIgMuyZ5mGzYWnzBYo9EmXZxKhd2qECfhLZQ7wqCWxq0JsCIAXOvxIxDFJPk1GdPIqp5JaDOMfQeefb3Pyu7E1yOsLjKvcDCFIQABoMMDA4MDc2MzYzNTE2Igyg7zKFUicnsOu76Rwq1AO9CJd8yFbubAzg2BLp3JPPBSh1Vo5A8FKRg7xEAqoHouJ%2Be8%2BRLQcIW2PXKR8GsRKMLWi2sH5aMp79tMqTMDkrBUgcg9EqMxQWIdpBRgezwLxn%2FleaC%2BRpgbL%2Bi9PmxN2kzKSVbUf7FdfwIu51yIoHGR8dBPz7AVqSZ5Kd06IoarHhpWMdKv8OZt%2Fz4vR2kpVzdRIw8ItBZ97LL6yuUR9WASZxdpW3Jalgq0z1s%2BYUal8%2FNTky%2Bw1MA%2BOP5A8%2BM3%2FqcB4nS5Sx6IVLZ9MHPvJXy4UlsP8f8eUuEN8CsfiOwJgQYG8QXibHPVNr8aHmOFQDa5VRD5neTDtyRUWIc44P2k%2FIL4aBaJuYMtgHd2G3fVRcuAyF%2BOQOQevJKZmaxkWPHT7HLKv6%2FPTVDaR7d4DJsfSV1YBQ0dpymHNQKY%2FFkPy8CKkJB4FUfCWfcl2UO3CQ0jEL2rzNgeFaK00afZqex10bYfODv%2BTlrIxjreb7myEat1DMtWL%2F9T18LmfI74r8A2nsUh1bS0DkDoJDmMimY3l5yIcjAXIAK7C4FwEPSdIegdXyWb05t8iB9yWnSkZZiVl1X2JwxH1ul2eQCkwEGsgQ6zjBd5UtjaOH21LgIRh0%2Fu8w%2BfGS%2BQU68AHF6%2Fum2%2BgCIHVlKOCmy9vq0diXepGvhBtF%2ByvRfxlctkedZH5SU4Rd7bgwmhSayi%2BoYBoRL4jSog4rUQGQDJizwQvw%2FfZRSjbf5fWxeWEulY0IqsOLx2m5n6wWlUmtBb6wlQ7O12MwguAIIORhoQRIAglAkTD7w4m0c7JIMYWBFfgNdETNlyhfjywYlD4o9T9IorPr5RVRnc%2BnqdzcIivqN1tNVQ37wTWab3CNFxNaUL5aAfw88PwKbkKoLYZ1ES9VrtTEYejAc3kqE3sx1ZjORW0IY3sQG2Qcc1A7n8sN49hguznL5A6zdJ0djUXHqUU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200801T023000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=9999&X-Amz-Credential=ASIAQDYLDQ36DH74BQ7K%2F20200801%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=0565fe4a363e9cf195dbff94ea835dfc7a7bc9de5d687080f7b0c420d9807fa2",
            "departmentName": "HaiTD",
            "positionName": null,
            "employeeSurnameKana": "PhuongBV",
            "employeeNameKana": null,
            "cellphoneNumber": "",
            "telephoneNumber": "",
            "email": "buivanphuong@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10022,
            "employeeName": null,
            "employeeSurname": "Phuong BV",
            "photoFilePath": "https://ms2-dev-files.s3.ap-northeast-1.amazonaws.com/tenants/mercyrrczkni/service_data/employee/10002_lemon_20200731124037638.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkYwRAIgMuyZ5mGzYWnzBYo9EmXZxKhd2qECfhLZQ7wqCWxq0JsCIAXOvxIxDFJPk1GdPIqp5JaDOMfQeefb3Pyu7E1yOsLjKvcDCFIQABoMMDA4MDc2MzYzNTE2Igyg7zKFUicnsOu76Rwq1AO9CJd8yFbubAzg2BLp3JPPBSh1Vo5A8FKRg7xEAqoHouJ%2Be8%2BRLQcIW2PXKR8GsRKMLWi2sH5aMp79tMqTMDkrBUgcg9EqMxQWIdpBRgezwLxn%2FleaC%2BRpgbL%2Bi9PmxN2kzKSVbUf7FdfwIu51yIoHGR8dBPz7AVqSZ5Kd06IoarHhpWMdKv8OZt%2Fz4vR2kpVzdRIw8ItBZ97LL6yuUR9WASZxdpW3Jalgq0z1s%2BYUal8%2FNTky%2Bw1MA%2BOP5A8%2BM3%2FqcB4nS5Sx6IVLZ9MHPvJXy4UlsP8f8eUuEN8CsfiOwJgQYG8QXibHPVNr8aHmOFQDa5VRD5neTDtyRUWIc44P2k%2FIL4aBaJuYMtgHd2G3fVRcuAyF%2BOQOQevJKZmaxkWPHT7HLKv6%2FPTVDaR7d4DJsfSV1YBQ0dpymHNQKY%2FFkPy8CKkJB4FUfCWfcl2UO3CQ0jEL2rzNgeFaK00afZqex10bYfODv%2BTlrIxjreb7myEat1DMtWL%2F9T18LmfI74r8A2nsUh1bS0DkDoJDmMimY3l5yIcjAXIAK7C4FwEPSdIegdXyWb05t8iB9yWnSkZZiVl1X2JwxH1ul2eQCkwEGsgQ6zjBd5UtjaOH21LgIRh0%2Fu8w%2BfGS%2BQU68AHF6%2Fum2%2BgCIHVlKOCmy9vq0diXepGvhBtF%2ByvRfxlctkedZH5SU4Rd7bgwmhSayi%2BoYBoRL4jSog4rUQGQDJizwQvw%2FfZRSjbf5fWxeWEulY0IqsOLx2m5n6wWlUmtBb6wlQ7O12MwguAIIORhoQRIAglAkTD7w4m0c7JIMYWBFfgNdETNlyhfjywYlD4o9T9IorPr5RVRnc%2BnqdzcIivqN1tNVQ37wTWab3CNFxNaUL5aAfw88PwKbkKoLYZ1ES9VrtTEYejAc3kqE3sx1ZjORW0IY3sQG2Qcc1A7n8sN49hguznL5A6zdJ0djUXHqUU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200801T023000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=9999&X-Amz-Credential=ASIAQDYLDQ36DH74BQ7K%2F20200801%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=0565fe4a363e9cf195dbff94ea835dfc7a7bc9de5d687080f7b0c420d9807fa2",
            "departmentName": "HaiTD",
            "positionName": null,
            "employeeSurnameKana": "PhuongBV",
            "employeeNameKana": null,
            "cellphoneNumber": "",
            "telephoneNumber": "",
            "email": "buivanphuong@luvina.net"
          },
          "createdDate": "2020-07-31T13:28:51.061925Z",
          "updatedDate": "2020-07-31T13:28:51.061925Z"
        }
      ],
      "total": 3
    },
    {
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress3\", \"zh_cn\": \"\"}",
      "productTradings": [
        {
          "productTradingId": 59,
          "customerName": null,
          "customerId": 18,
          "productId": 65,
          "productName": "商品15237_2",
          "quantity": 1000,
          "price": 1200,
          "amount": 1200000,
          "productTradingProgressId": 3,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress3\", \"zh_cn\": \"\"}",
          "progressOrder": 3,
          "isAvailable": true,
          "endPlanDate": "2020-07-14T00:00:00Z",
          "orderPlanDate": "2020-07-16T00:00:00Z",
          "memo": "MeMoY",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1226,
            "amount": 1200000,
            "contentChange": "{\"product_trading_progress_id\": {\"new\": \"3\", \"old\": \"5\"}}",
            "endPlanDate": "2020-07-14T00:00:00Z",
            "memo": "MeMoY",
            "orderPlanDate": "2020-07-16T00:00:00Z",
            "productTradingId": 59,
            "productId": 65,
            "price": 1200,
            "productTradingProgressId": 5,
            "productTradingData": "{}",
            "quantity": 1000,
            "activityId": 171,
            "createdDate": "2020-07-31T14:13:42.794592Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T14:13:42.794592Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T12:33:25.144582Z",
          "updatedDate": "2020-07-31T14:13:42.794592Z"
        },
        {
          "productTradingId": 64,
          "customerName": null,
          "customerId": 20,
          "productId": 114,
          "productName": "商品A",
          "quantity": 2,
          "price": 100,
          "amount": 200,
          "productTradingProgressId": 3,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress3\", \"zh_cn\": \"\"}",
          "progressOrder": 3,
          "isAvailable": true,
          "endPlanDate": "2020-07-08T00:00:00Z",
          "orderPlanDate": "2020-07-15T00:00:00Z",
          "memo": "メモ1",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1221,
            "amount": 200,
            "contentChange": null,
            "endPlanDate": "2020-07-08T00:00:00Z",
            "memo": "メモ1",
            "orderPlanDate": "2020-07-15T00:00:00Z",
            "productTradingId": 64,
            "productId": 114,
            "price": 100,
            "productTradingProgressId": 3,
            "productTradingData": "{}",
            "quantity": 2,
            "activityId": 173,
            "createdDate": "2020-07-31T13:26:36.893947Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T13:26:36.893947Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T13:26:36.893947Z",
          "updatedDate": "2020-07-31T13:26:36.893947Z"
        }
      ],
      "total": 2
    },
    {
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress 4\", \"zh_cn\": \"\"}",
      "productTradings": [
        {
          "productTradingId": 68,
          "customerName": null,
          "customerId": 19,
          "productId": 113,
          "productName": "商品A",
          "quantity": 22,
          "price": 222,
          "amount": 4884,
          "productTradingProgressId": 4,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress 4\", \"zh_cn\": \"\"}",
          "progressOrder": 4,
          "isAvailable": true,
          "endPlanDate": "2020-07-15T00:00:00Z",
          "orderPlanDate": "2020-07-24T00:00:00Z",
          "memo": "メモ商品",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1225,
            "amount": 4884,
            "contentChange": null,
            "endPlanDate": "2020-07-15T00:00:00Z",
            "memo": "メモ商品",
            "orderPlanDate": "2020-07-24T00:00:00Z",
            "productTradingId": 68,
            "productId": 113,
            "price": 222,
            "productTradingProgressId": 4,
            "productTradingData": "{}",
            "quantity": 22,
            "activityId": 174,
            "createdDate": "2020-07-31T13:28:51.061925Z",
            "createdUser": 10022,
            "updatedDate": "2020-07-31T13:28:51.061925Z",
            "updatedUser": 10022
          },
          "employee": {
            "employeeId": 10022,
            "employeeName": null,
            "employeeSurname": "Phuong BV",
            "photoFilePath": "https://ms2-dev-files.s3.ap-northeast-1.amazonaws.com/tenants/mercyrrczkni/service_data/employee/10002_lemon_20200731124037638.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkYwRAIgMuyZ5mGzYWnzBYo9EmXZxKhd2qECfhLZQ7wqCWxq0JsCIAXOvxIxDFJPk1GdPIqp5JaDOMfQeefb3Pyu7E1yOsLjKvcDCFIQABoMMDA4MDc2MzYzNTE2Igyg7zKFUicnsOu76Rwq1AO9CJd8yFbubAzg2BLp3JPPBSh1Vo5A8FKRg7xEAqoHouJ%2Be8%2BRLQcIW2PXKR8GsRKMLWi2sH5aMp79tMqTMDkrBUgcg9EqMxQWIdpBRgezwLxn%2FleaC%2BRpgbL%2Bi9PmxN2kzKSVbUf7FdfwIu51yIoHGR8dBPz7AVqSZ5Kd06IoarHhpWMdKv8OZt%2Fz4vR2kpVzdRIw8ItBZ97LL6yuUR9WASZxdpW3Jalgq0z1s%2BYUal8%2FNTky%2Bw1MA%2BOP5A8%2BM3%2FqcB4nS5Sx6IVLZ9MHPvJXy4UlsP8f8eUuEN8CsfiOwJgQYG8QXibHPVNr8aHmOFQDa5VRD5neTDtyRUWIc44P2k%2FIL4aBaJuYMtgHd2G3fVRcuAyF%2BOQOQevJKZmaxkWPHT7HLKv6%2FPTVDaR7d4DJsfSV1YBQ0dpymHNQKY%2FFkPy8CKkJB4FUfCWfcl2UO3CQ0jEL2rzNgeFaK00afZqex10bYfODv%2BTlrIxjreb7myEat1DMtWL%2F9T18LmfI74r8A2nsUh1bS0DkDoJDmMimY3l5yIcjAXIAK7C4FwEPSdIegdXyWb05t8iB9yWnSkZZiVl1X2JwxH1ul2eQCkwEGsgQ6zjBd5UtjaOH21LgIRh0%2Fu8w%2BfGS%2BQU68AHF6%2Fum2%2BgCIHVlKOCmy9vq0diXepGvhBtF%2ByvRfxlctkedZH5SU4Rd7bgwmhSayi%2BoYBoRL4jSog4rUQGQDJizwQvw%2FfZRSjbf5fWxeWEulY0IqsOLx2m5n6wWlUmtBb6wlQ7O12MwguAIIORhoQRIAglAkTD7w4m0c7JIMYWBFfgNdETNlyhfjywYlD4o9T9IorPr5RVRnc%2BnqdzcIivqN1tNVQ37wTWab3CNFxNaUL5aAfw88PwKbkKoLYZ1ES9VrtTEYejAc3kqE3sx1ZjORW0IY3sQG2Qcc1A7n8sN49hguznL5A6zdJ0djUXHqUU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200801T023000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=9999&X-Amz-Credential=ASIAQDYLDQ36DH74BQ7K%2F20200801%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=0565fe4a363e9cf195dbff94ea835dfc7a7bc9de5d687080f7b0c420d9807fa2",
            "departmentName": "HaiTD",
            "positionName": null,
            "employeeSurnameKana": "PhuongBV",
            "employeeNameKana": null,
            "cellphoneNumber": "",
            "telephoneNumber": "",
            "email": "buivanphuong@luvina.net"
          },
          "createdUser": {
            "employeeId": 10022,
            "employeeName": null,
            "employeeSurname": "Phuong BV",
            "photoFilePath": "https://ms2-dev-files.s3.ap-northeast-1.amazonaws.com/tenants/mercyrrczkni/service_data/employee/10002_lemon_20200731124037638.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkYwRAIgMuyZ5mGzYWnzBYo9EmXZxKhd2qECfhLZQ7wqCWxq0JsCIAXOvxIxDFJPk1GdPIqp5JaDOMfQeefb3Pyu7E1yOsLjKvcDCFIQABoMMDA4MDc2MzYzNTE2Igyg7zKFUicnsOu76Rwq1AO9CJd8yFbubAzg2BLp3JPPBSh1Vo5A8FKRg7xEAqoHouJ%2Be8%2BRLQcIW2PXKR8GsRKMLWi2sH5aMp79tMqTMDkrBUgcg9EqMxQWIdpBRgezwLxn%2FleaC%2BRpgbL%2Bi9PmxN2kzKSVbUf7FdfwIu51yIoHGR8dBPz7AVqSZ5Kd06IoarHhpWMdKv8OZt%2Fz4vR2kpVzdRIw8ItBZ97LL6yuUR9WASZxdpW3Jalgq0z1s%2BYUal8%2FNTky%2Bw1MA%2BOP5A8%2BM3%2FqcB4nS5Sx6IVLZ9MHPvJXy4UlsP8f8eUuEN8CsfiOwJgQYG8QXibHPVNr8aHmOFQDa5VRD5neTDtyRUWIc44P2k%2FIL4aBaJuYMtgHd2G3fVRcuAyF%2BOQOQevJKZmaxkWPHT7HLKv6%2FPTVDaR7d4DJsfSV1YBQ0dpymHNQKY%2FFkPy8CKkJB4FUfCWfcl2UO3CQ0jEL2rzNgeFaK00afZqex10bYfODv%2BTlrIxjreb7myEat1DMtWL%2F9T18LmfI74r8A2nsUh1bS0DkDoJDmMimY3l5yIcjAXIAK7C4FwEPSdIegdXyWb05t8iB9yWnSkZZiVl1X2JwxH1ul2eQCkwEGsgQ6zjBd5UtjaOH21LgIRh0%2Fu8w%2BfGS%2BQU68AHF6%2Fum2%2BgCIHVlKOCmy9vq0diXepGvhBtF%2ByvRfxlctkedZH5SU4Rd7bgwmhSayi%2BoYBoRL4jSog4rUQGQDJizwQvw%2FfZRSjbf5fWxeWEulY0IqsOLx2m5n6wWlUmtBb6wlQ7O12MwguAIIORhoQRIAglAkTD7w4m0c7JIMYWBFfgNdETNlyhfjywYlD4o9T9IorPr5RVRnc%2BnqdzcIivqN1tNVQ37wTWab3CNFxNaUL5aAfw88PwKbkKoLYZ1ES9VrtTEYejAc3kqE3sx1ZjORW0IY3sQG2Qcc1A7n8sN49hguznL5A6zdJ0djUXHqUU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200801T023000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=9999&X-Amz-Credential=ASIAQDYLDQ36DH74BQ7K%2F20200801%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=0565fe4a363e9cf195dbff94ea835dfc7a7bc9de5d687080f7b0c420d9807fa2",
            "departmentName": "HaiTD",
            "positionName": null,
            "employeeSurnameKana": "PhuongBV",
            "employeeNameKana": null,
            "cellphoneNumber": "",
            "telephoneNumber": "",
            "email": "buivanphuong@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10022,
            "employeeName": null,
            "employeeSurname": "Phuong BV",
            "photoFilePath": "https://ms2-dev-files.s3.ap-northeast-1.amazonaws.com/tenants/mercyrrczkni/service_data/employee/10002_lemon_20200731124037638.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkYwRAIgMuyZ5mGzYWnzBYo9EmXZxKhd2qECfhLZQ7wqCWxq0JsCIAXOvxIxDFJPk1GdPIqp5JaDOMfQeefb3Pyu7E1yOsLjKvcDCFIQABoMMDA4MDc2MzYzNTE2Igyg7zKFUicnsOu76Rwq1AO9CJd8yFbubAzg2BLp3JPPBSh1Vo5A8FKRg7xEAqoHouJ%2Be8%2BRLQcIW2PXKR8GsRKMLWi2sH5aMp79tMqTMDkrBUgcg9EqMxQWIdpBRgezwLxn%2FleaC%2BRpgbL%2Bi9PmxN2kzKSVbUf7FdfwIu51yIoHGR8dBPz7AVqSZ5Kd06IoarHhpWMdKv8OZt%2Fz4vR2kpVzdRIw8ItBZ97LL6yuUR9WASZxdpW3Jalgq0z1s%2BYUal8%2FNTky%2Bw1MA%2BOP5A8%2BM3%2FqcB4nS5Sx6IVLZ9MHPvJXy4UlsP8f8eUuEN8CsfiOwJgQYG8QXibHPVNr8aHmOFQDa5VRD5neTDtyRUWIc44P2k%2FIL4aBaJuYMtgHd2G3fVRcuAyF%2BOQOQevJKZmaxkWPHT7HLKv6%2FPTVDaR7d4DJsfSV1YBQ0dpymHNQKY%2FFkPy8CKkJB4FUfCWfcl2UO3CQ0jEL2rzNgeFaK00afZqex10bYfODv%2BTlrIxjreb7myEat1DMtWL%2F9T18LmfI74r8A2nsUh1bS0DkDoJDmMimY3l5yIcjAXIAK7C4FwEPSdIegdXyWb05t8iB9yWnSkZZiVl1X2JwxH1ul2eQCkwEGsgQ6zjBd5UtjaOH21LgIRh0%2Fu8w%2BfGS%2BQU68AHF6%2Fum2%2BgCIHVlKOCmy9vq0diXepGvhBtF%2ByvRfxlctkedZH5SU4Rd7bgwmhSayi%2BoYBoRL4jSog4rUQGQDJizwQvw%2FfZRSjbf5fWxeWEulY0IqsOLx2m5n6wWlUmtBb6wlQ7O12MwguAIIORhoQRIAglAkTD7w4m0c7JIMYWBFfgNdETNlyhfjywYlD4o9T9IorPr5RVRnc%2BnqdzcIivqN1tNVQ37wTWab3CNFxNaUL5aAfw88PwKbkKoLYZ1ES9VrtTEYejAc3kqE3sx1ZjORW0IY3sQG2Qcc1A7n8sN49hguznL5A6zdJ0djUXHqUU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200801T023000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=9999&X-Amz-Credential=ASIAQDYLDQ36DH74BQ7K%2F20200801%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=0565fe4a363e9cf195dbff94ea835dfc7a7bc9de5d687080f7b0c420d9807fa2",
            "departmentName": "HaiTD",
            "positionName": null,
            "employeeSurnameKana": "PhuongBV",
            "employeeNameKana": null,
            "cellphoneNumber": "",
            "telephoneNumber": "",
            "email": "buivanphuong@luvina.net"
          },
          "createdDate": "2020-07-31T13:28:51.061925Z",
          "updatedDate": "2020-07-31T13:28:51.061925Z"
        },
        {
          "productTradingId": 66,
          "customerName": null,
          "customerId": 20,
          "productId": 77,
          "productName": "商品A100",
          "quantity": 4,
          "price": 1777,
          "amount": 7108,
          "productTradingProgressId": 4,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress 4\", \"zh_cn\": \"\"}",
          "progressOrder": 4,
          "isAvailable": true,
          "endPlanDate": "2020-07-15T00:00:00Z",
          "orderPlanDate": "2020-07-24T00:00:00Z",
          "memo": "MeMoX",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1223,
            "amount": 7108,
            "contentChange": null,
            "endPlanDate": "2020-07-15T00:00:00Z",
            "memo": "MeMoX",
            "orderPlanDate": "2020-07-24T00:00:00Z",
            "productTradingId": 66,
            "productId": 77,
            "price": 1777,
            "productTradingProgressId": 4,
            "productTradingData": "{}",
            "quantity": 4,
            "activityId": 173,
            "createdDate": "2020-07-31T13:26:36.893947Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T13:26:36.893947Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T13:26:36.893947Z",
          "updatedDate": "2020-07-31T13:26:36.893947Z"
        },
        {
          "productTradingId": 63,
          "customerName": null,
          "customerId": 20,
          "productId": 65,
          "productName": "商品15237_2",
          "quantity": 1,
          "price": 1000,
          "amount": 1000,
          "productTradingProgressId": 4,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress 4\", \"zh_cn\": \"\"}",
          "progressOrder": 4,
          "isAvailable": true,
          "endPlanDate": "2020-07-08T00:00:00Z",
          "orderPlanDate": "2020-07-01T00:00:00Z",
          "memo": "MeMoX",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1227,
            "amount": 1000,
            "contentChange": "{\"product_trading_progress_id\": {\"new\": \"4\", \"old\": \"2\"}}",
            "endPlanDate": "2020-07-08T00:00:00Z",
            "memo": "MeMoX",
            "orderPlanDate": "2020-07-01T00:00:00Z",
            "productTradingId": 63,
            "productId": 65,
            "price": 1000,
            "productTradingProgressId": 2,
            "productTradingData": "{}",
            "quantity": 1,
            "activityId": 173,
            "createdDate": "2020-07-31T15:27:23.290329Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T15:27:23.290329Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T13:26:36.893947Z",
          "updatedDate": "2020-07-31T15:27:23.290329Z"
        }
      ],
      "total": 3
    },
    {
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress5\", \"zh_cn\": \"\"}",
      "productTradings": [
        {
          "productTradingId": 62,
          "customerName": null,
          "customerId": 21,
          "productId": 112,
          "productName": "商品6368",
          "quantity": 8,
          "price": 16666,
          "amount": 133328,
          "productTradingProgressId": 5,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress5\", \"zh_cn\": \"\"}",
          "progressOrder": 5,
          "isAvailable": true,
          "endPlanDate": "2020-07-21T00:00:00Z",
          "orderPlanDate": "2020-07-23T00:00:00Z",
          "memo": "メモ商品",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1219,
            "amount": 133328,
            "contentChange": null,
            "endPlanDate": "2020-07-21T00:00:00Z",
            "memo": "メモ商品",
            "orderPlanDate": "2020-07-23T00:00:00Z",
            "productTradingId": 62,
            "productId": 112,
            "price": 16666,
            "productTradingProgressId": 5,
            "productTradingData": "{}",
            "quantity": 8,
            "activityId": 172,
            "createdDate": "2020-07-31T13:20:53.808582Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T13:20:53.808582Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T13:20:53.808582Z",
          "updatedDate": "2020-07-31T13:20:53.808582Z"
        },
        {
          "productTradingId": 57,
          "customerName": null,
          "customerId": 18,
          "productId": 49,
          "productName": "セット商品A",
          "quantity": 16,
          "price": 1000,
          "amount": 16000,
          "productTradingProgressId": 5,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress5\", \"zh_cn\": \"\"}",
          "progressOrder": 5,
          "isAvailable": true,
          "endPlanDate": "2020-07-24T00:00:00Z",
          "orderPlanDate": "2020-07-15T00:00:00Z",
          "memo": "memo",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1206,
            "amount": 16000,
            "contentChange": null,
            "endPlanDate": "2020-07-24T00:00:00Z",
            "memo": "memo",
            "orderPlanDate": "2020-07-15T00:00:00Z",
            "productTradingId": 57,
            "productId": 49,
            "price": 1000,
            "productTradingProgressId": 5,
            "productTradingData": "{}",
            "quantity": 16,
            "activityId": 170,
            "createdDate": "2020-07-31T12:28:23.317679Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T12:28:23.317679Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T12:28:23.317679Z",
          "updatedDate": "2020-07-31T12:28:23.317679Z"
        }
      ],
      "total": 2
    },
    {
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress7\", \"zh_cn\": \"\"}",
      "productTradings": [
        {
          "productTradingId": 65,
          "customerName": null,
          "customerId": 20,
          "productId": 86,
          "productName": "商品A100",
          "quantity": 40,
          "price": 111,
          "amount": 4440,
          "productTradingProgressId": 6,
          "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress7\", \"zh_cn\": \"\"}",
          "progressOrder": 6,
          "isAvailable": true,
          "endPlanDate": "2020-07-14T00:00:00Z",
          "orderPlanDate": "2020-07-15T00:00:00Z",
          "memo": "MeMoX",
          "productTradingData": [],
          "productTradingHistories": null,
          "productTradingHistory": {
            "productTradingHistoryId": 1222,
            "amount": 4440,
            "contentChange": null,
            "endPlanDate": "2020-07-14T00:00:00Z",
            "memo": "MeMoX",
            "orderPlanDate": "2020-07-15T00:00:00Z",
            "productTradingId": 65,
            "productId": 86,
            "price": 111,
            "productTradingProgressId": 6,
            "productTradingData": "{}",
            "quantity": 40,
            "activityId": 173,
            "createdDate": "2020-07-31T13:26:36.893947Z",
            "createdUser": 10002,
            "updatedDate": "2020-07-31T13:26:36.893947Z",
            "updatedUser": 10002
          },
          "employee": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "updatedUser": {
            "employeeId": 10002,
            "employeeName": "VuLQ",
            "employeeSurname": "Team",
            "photoFilePath": null,
            "departmentName": "HaiTD",
            "positionName": "{\"en_us\": \"Boss\"}",
            "employeeSurnameKana": "TEAM",
            "employeeNameKana": "VULQ",
            "cellphoneNumber": "",
            "telephoneNumber": "034856987",
            "email": "teamvu@luvina.net"
          },
          "createdDate": "2020-07-31T13:26:36.893947Z",
          "updatedDate": "2020-07-31T13:26:36.893947Z"
        }
      ],
      "total": 1
    }
  ],
  "progresses": [
    {
      "productTradingProgressId": 1,
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress6\", \"zh_cn\": \"\"}",
      "isAvailable": true,
      "progressOrder": 1
    },
    {
      "productTradingProgressId": 2,
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress1\", \"zh_cn\": \"\"}",
      "isAvailable": true,
      "progressOrder": 2
    },
    {
      "productTradingProgressId": 3,
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress3\", \"zh_cn\": \"\"}",
      "isAvailable": true,
      "progressOrder": 3
    },
    {
      "productTradingProgressId": 4,
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress 4\", \"zh_cn\": \"\"}",
      "isAvailable": true,
      "progressOrder": 4
    },
    {
      "productTradingProgressId": 5,
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress5\", \"zh_cn\": \"\"}",
      "isAvailable": true,
      "progressOrder": 5
    },
    {
      "productTradingProgressId": 6,
      "progressName": "{\"en_us\": \"\", \"ja_jp\": \"Progress7\", \"zh_cn\": \"\"}",
      "isAvailable": true,
      "progressOrder": 6
    }
  ],
  "initializeInfo": null,
  "fieldInfo": [
    {
      "fieldId": 170,
      "fieldName": "product_trading_id",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 171,
      "fieldName": "customer_id",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 172,
      "fieldName": "product_id",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 173,
      "fieldName": "quantity",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 205,
      "fieldName": "scenario_id",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 174,
      "fieldName": "price",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 175,
      "fieldName": "amount",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 176,
      "fieldName": "product_trading_progress_id",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 177,
      "fieldName": "order_plan_date",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 178,
      "fieldName": "end_plan_date",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 179,
      "fieldName": "memo",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 180,
      "fieldName": "employee_id",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 181,
      "fieldName": "created_date",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 182,
      "fieldName": "created_user",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 183,
      "fieldName": "updated_date",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    },
    {
      "fieldId": 184,
      "fieldName": "updated_user",
      "forwardColor": null,
      "forwardText": null,
      "backwardText": null,
      "backwardColor": null,
      "fieldLabel": null,
      "isDefault": true,
      "currencyUnit": null
    }
  ]
};