export const dataGetBusinessCardsDummy = {
  businessCards: [
    {
      id: 1,
      department: "部署A",
      manager: "社員A部長",
      check: false,
      species: "閲覧者",
      position: "五十嵐光太郎 部長",
    },
    {
      id: 2,
      department: "部署B",
      manager: "社員B部長",
      check: false,
      species: "閲覧者",
      position: "山田太郎 課長",
    },
    {
      id: 3,
      department: "部署C",
      manager: "社員C部長",
      check: false,
      species: "閲覧者",
      position: "山田太郎 課長",
    },
    {
      id: 4,
      department: "部署D",
      manager: "社員D部長",
      check: false,
      species: "閲覧者",
      position: "五十嵐光太郎 部長",
    },
    // {
    //   id: 5,
    //   department: "部署A",
    //   manager: "社員A部長",
    //   check: false,
    //   species: "閲覧者",
    //   position: "山田太郎 課長",
    // },
    // {
    //   id: 6,
    //   department: "部署A",
    //   manager: "社員A部長",
    //   check: false,
    //   species: "閲覧者",
    //   position: "五十嵐光太郎 部長",
    // },
    // {
    //   id: 7,
    //   department: "部署A",
    //   manager: "社員A部長",
    //   check: false,
    //   species: "閲覧者",
    //   position: "山田太郎 課長",
    // },
  ],
};

export const dataGetBusinessCardsSuggestionDummy = {
  listInfo: [
    {
      listId: 3001,
      employeeName: "3001",
      listName: "Mylist1",
      displayOrder: 1,
      listType: 1,
      employeeSurname: "surName",
      displayOrderFavoriteList: 1,
    },
    {
      listId: 3002,
      employeeName: "3002",
      listName: "shareList1",
      displayOrder: 2,
      listType: 2,
      employeeSurname: "surName",
      displayOrderFavoriteList: 2,
    },
    {
      listId: 3003,
      employeeName: "3003",
      listName: "shareList2",
      displayOrder: 3,
      listType: 2,
      employeeSurname: "surName",
      displayOrderFavoriteList: 3,
    },
    {
      listId: 3004,
      employeeName: "3004",
      listName: "shareList3",
      displayOrder: 4,
      listType: 2,
      employeeSurname: "surName",
      displayOrderFavoriteList: 4,
    },
    {
      listId: 3005,
      employeeName: "3005",
      listName: "Mylist2",
      displayOrder: 5,
      listType: 1,
      employeeSurname: "surName",
      displayOrderFavoriteList: 5,
    },
    {
      listId: 3006,
      employeeName: "3006",
      listName: "Mylist3",
      displayOrder: 6,
      listType: 1,
      employeeSurname: "surName",
      displayOrderFavoriteList: 6,
    },
  ],
};
