const APIGATEWAY_ADDRESS = process.env.APIGATEWAY_ADDRESS;
const COGNITO_USER_POOL_ID = process.env.COGNITO_USER_POOL_ID;
const COGNITO_CLIENT_ID = process.env.COGNITO_CLIENT_ID;
const AWS_ACCOUNT_ID = process.env.AWS_ACCOUNT_ID;
const S3_CFNTEMPLATE_BUCKET_URL = process.env.S3_CFNTEMPLATE_BUCKET_URL
const COMMIT_TAG = process.env.COMMIT_TAG
export default {
    'APIGATEWAY_ADDRESS': APIGATEWAY_ADDRESS,
    'COGNITO_USER_POOL_ID': COGNITO_USER_POOL_ID,
    'COGNITO_CLIENT_ID': COGNITO_CLIENT_ID,
    'AWS_ACCOUNT_ID': AWS_ACCOUNT_ID,
    'S3_CFNTEMPLATE_BUCKET_URL': S3_CFNTEMPLATE_BUCKET_URL,
    'COMMIT_TAG': COMMIT_TAG
}
