@startuml{レポート一覧画面.png}
title [レポート一覧画面]
hide footbox

actor ユーザー as user
boundary レポート一覧画面 as view
participant レポートAPI as api_reports #cyan
database レポートストレージ as storage <<s3>> #crimson

== 表示 ==
user -> view :表示
activate view
    view -> api_reports :GET /organizations/{organization_id}/projects/{project_id}/reports
    activate api_reports
        api_reports --> view :200:レポートリスト
    deactivate api_reports
    view -> view :画面描画
    view --> user
deactivate view

== レポート出力 ==
user -> view :レポート出力
activate view
    view -> api_reports :POST /organizations/{organization_id}/projects/{project_id}/reports/{report_id}/report/output
    activate api_reports
        api_reports --> view :200
    deactivate api_reports
    view --> user
deactivate view

== レポートダウンロード ==
user -> view :レポート出力
activate view
    view -> api_reports :GET /organizations/{organization_id}/projects/{project_id}/reports/{report_id}/report
    activate api_reports
        api_reports --> view :200:レポートファイルURL
    deactivate api_reports
    |||
    view -> storage :ダウンロード
    storage --> view :200:レポートファイル
    view --> user
deactivate view

@enduml
