import {StyleSheet } from "react-native";
import { theme } from "../../../config/constants";

export const DrawerTaskStyle = StyleSheet.create({
  rowView: {
    paddingLeft: theme.space[4],
    paddingRight: theme.space[5],
  },
  textCommonStyle: {
    fontSize: theme.space[4],
  },
  container: {
    flexDirection: "row",
    width: "100%",
    paddingVertical: theme.space[5],
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: theme.colors.gray100,
  },
  customerContain: {
    paddingVertical: theme.space[5],
    borderBottomWidth: 1,
    borderColor: theme.colors.gray100,
  },
  customerList: { paddingLeft: theme.space[3] },
  customerName: { marginTop: theme.space[5] },
  searchContainer: {
    paddingVertical: theme.space[5],
    borderBottomWidth: 1,
    borderColor: theme.colors.gray100,
    paddingLeft: theme.space[10],
  },
  inputContainer: {
    marginTop: theme.space[4],
    borderRadius: 12,
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0.5,
    borderColor: theme.colors.gray100,
    paddingRight: theme.space[1],
  },
  searchIcon: {
    width: 20,
    height: 20,
    marginLeft: theme.space[5],
  },
  inputText: {
    backgroundColor: "#F9F9F9",
    flex: 1,
    borderWidth: 0,
    borderRadius: theme.borderRadius,
  },
  customerListTask: {
    paddingVertical: theme.space[5],
    paddingLeft: theme.space[4],
    paddingRight: theme.space[5],
    borderBottomWidth: 1,
    borderColor: theme.colors.gray100,
  },
  customersFavourite: {
    paddingLeft: theme.space[3],
  },
  customersFavouriteListName: { marginTop: theme.space[5] },
  personInCharge: {
    paddingVertical: theme.space[5],
    paddingRight: theme.space[5],
    borderBottomWidth: 1,
    borderColor: theme.colors.gray100,
    paddingLeft: theme.space[10],
  },
  specifyPeriod: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: theme.space[4],
    paddingRight: theme.space[5],
    paddingVertical: theme.space[5],
  },
  fab: {
    width: theme.floatingButton,
    aspectRatio: 1,
    borderRadius: theme.floatingButton / 2,
    backgroundColor: theme.colors.white,
    shadowColor: theme.colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    // position: "absolute",
    // top: getScreenHeight() - theme.floatingButton - theme.space[18],
    // right: theme.space[3],
    justifyContent: "center",
    alignItems: "center",
  },
  fabIcon: {
    width: theme.space[6],
    height: theme.space[6],
  },
  fabBtnContainer: {
    zIndex: 1,
    width: 60,
    height: 60,
    position: "absolute",
    bottom: "10%",
    alignItems: "center",
    justifyContent: "center",
    right: 10,
  },
  containerModal: {
    backgroundColor: "rgba(0,0,0,0.8)",
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: "10%",
  },
  contentModal: {
    width: "100%",
    height: 100,
    borderRadius: theme.space[4],
    backgroundColor: theme.colors.white,
  },
  btnAddTask: {
    flex: 1,
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.gray250,
    alignItems: "center",
  },
  btnAddMilestone: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  txtModal: {
    fontSize: theme.fontSizes[3],
    color: theme.colors.black,
  },
});
