export const DUMMY_CALENDAR_LIST = {
  dateFromData: "2019/08/01",
  dateToData: "2019/10/01",
  isGetMoreData: 1,
  dateList: [
    {
      date: "2019/06/05",
      perpetualCalendar: "先勝",
      holidayName: "祝日",
      isHoliday: 0,
      isCompanyHoliday: 0,
      companyHolidayName: null,
    },
    {
      date: "2019/06/06",
      perpetualCalendar: "先勝",
      holidayName: null,
      isHoliday: 0,
      isCompanyHoliday: 0,
      companyHolidayName: null,
    },
    {
      date: "2019/06/07",
      perpetualCalendar: "先勝",
      holidayName: "祝日",
      isHoliday: 0,
      isCompanyHoliday: 1,
      companyHolidayName: "創立記念日",
    },
    {
      date: "2020/06/08",
      perpetualCalendar: "先勝",
      holidayName: "祝日",
      isHoliday: 1,
      isCompanyHoliday: 0,
      companyHolidayName: null,
    },
    {
      date: "2020/06/09",
      perpetualCalendar: "先勝",
      holidayName: "祝日",
      isHoliday: 0,
      isCompanyHoliday: 0,
      companyHolidayName: null,
    },
  ],
  itemList: [
    {
      itemType: 1,
      itemId: 123456,
      itemName: "Milestone Name1",
      employeeId: 2221,
      startDate: null,
      finishDate: "2020-06-12T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: null,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 0,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: "01",
      taskStatus: null,
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 1,
      itemId: 123457,
      itemName: "Milestone Name2",
      employeeId: 2221,
      startDate: null,
      finishDate: "2020-06-12T21:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: null,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 1,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: "02",
      taskStatus: null,
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 1,
      itemId: 123458,
      itemName: "Milestone Name3",
      employeeId: 2221,
      startDate: null,
      finishDate: "2020-06-12T22:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: null,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 1,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: "00",
      taskStatus: null,
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },

    {
      itemType: 2,
      itemId: 22209,
      itemName: "Task Name1",
      employeeId: 2221,
      startDate: "2020-06-09T23:59:59Z",
      finishDate: "2020-06-10T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: 1,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 0,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: null,
      taskStatus: "00",
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 2,
      itemId: 22209,
      itemName: "Task Name1",
      employeeId: 2221,
      startDate: "2020-06-09T23:59:59Z",
      finishDate: "2020-06-10T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: 1,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 0,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: null,
      taskStatus: "01",
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 2,
      itemId: 22209,
      itemName: "Task Name1",
      employeeId: 2221,
      startDate: "2020-06-09T23:59:59Z",
      finishDate: "2020-06-10T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: 1,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 0,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: null,
      taskStatus: "02",
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 2,
      itemId: 22209,
      itemName: "Task Name1",
      employeeId: 2221,
      startDate: "2020-06-09T23:59:59Z",
      finishDate: "2020-06-10T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: 1,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 1,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: null,
      taskStatus: "00",
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 2,
      itemId: 22209,
      itemName: "Task Name2",
      employeeId: 2221,
      startDate: "2020-06-09T23:59:59Z",
      finishDate: "2020-06-10T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: 1,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 1,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: null,
      taskStatus: "01",
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 2,
      itemId: 22209,
      itemName: "Task Name3",
      employeeId: 2221,
      startDate: "2020-06-09T23:59:59Z",
      finishDate: "2020-06-10T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: 1,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 1,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: null,
      taskStatus: "02",
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 2,
      itemId: 22209,
      itemName: "Task Name4",
      employeeId: 2221,
      startDate: "2020-06-09T23:59:59Z",
      finishDate: "2020-06-10T23:59:59Z",
      itemIcon: null,
      isFullDay: 1,
      isOverDay: 1,
      isRepeat: null,
      scheduleRepeatId: null,
      scheduleTypeId: null,
      isPublic: 1,
      isReportActivity: null,
      isParticipantUser: 0,
      isDuplicate: null,
      milestoneStatus: null,
      taskStatus: "02",
      participationDivision: null,
      attendanceDivision: null,
      customers: [],
      productTradings: [],
      businessCards: [],
    },
    {
      itemType: 3,
      itemId: 123456,
      itemName: "Schedule Name1",
      employeeId: 332,
      startDate: "2020-06-12T23:59:59Z",
      endDate: "2020-06-13T23:59:59Z",
      itemIcon: "\\image\\damphan.png",
      isFullDay: 1,
      isOverDay: 0,
      isRepeat: 0,
      scheduleRepeatId: null,
      scheduleTypeId: 1,
      isPublic: 1,
      isReportActivity: 0,
      isParticipantUser: 0,
      isDuplicate: 1,
      milestoneStatus: null,
      taskStatus: null,
      participationDivision: "00",
      attendanceDivision: "00",

      customers: [],
      productTradings: [
        {
          productTradingId: 4446,
          productId: 31,
          productName: "商品名3",
        },
      ],
      businessCards: [
        {
          businessCardId: 33356,
          businessCardName: "名刺名1",
        },
      ],
    },
    {
      itemType: 3,
      itemId: 123456,
      itemName: "Schedule Name1",
      employeeId: 332,
      startDate: "2020-06-12T23:59:59Z",
      endDate: "2020-06-13T23:59:59Z",
      itemIcon: "\\image\\damphan.png",
      isFullDay: 1,
      isOverDay: 0,
      isRepeat: 0,
      scheduleRepeatId: null,
      scheduleTypeId: 1,
      isPublic: 1,
      isReportActivity: 0,
      isParticipantUser: 0,
      isDuplicate: 1,
      milestoneStatus: null,
      taskStatus: null,
      participationDivision: "00",
      attendanceDivision: "00",

      customers: [],
      productTradings: [
        {
          productTradingId: 4446,
          productId: 31,
          productName: "商品名3",
        },
      ],
      businessCards: [
        {
          businessCardId: 33356,
          businessCardName: "名刺名1",
        },
      ],
    },
    {
      itemType: 3,
      itemId: 123456,
      itemName: "Schedule Name2",
      employeeId: 332,
      startDate: "2020-06-12T23:59:59Z",
      endDate: "2020-06-13T23:59:59Z",
      itemIcon: "\\image\\damphan.png",
      isFullDay: 1,
      isOverDay: 0,
      isRepeat: 0,
      scheduleRepeatId: null,
      scheduleTypeId: 1,
      isPublic: 1,
      isReportActivity: 0,
      isParticipantUser: 0,
      isDuplicate: 1,
      milestoneStatus: null,
      taskStatus: null,
      participationDivision: "00",
      attendanceDivision: "00",

      customers: [],
      productTradings: [
        {
          productTradingId: 4446,
          productId: 31,
          productName: "商品名3",
        },
      ],
      businessCards: [
        {
          businessCardId: 33356,
          businessCardName: "名刺名1",
        },
      ],
    },
    {
      itemType: 3,
      itemId: 123456,
      itemName: "Schedule Name3",
      employeeId: 332,
      startDate: "2020-06-12T23:59:59Z",
      endDate: "2020-06-13T23:59:59Z",
      itemIcon: "\\image\\damphan.png",
      isFullDay: 1,
      isOverDay: 0,
      isRepeat: 0,
      scheduleRepeatId: null,
      scheduleTypeId: 1,
      isPublic: 0,
      isReportActivity: 1,
      isParticipantUser: 0,
      isDuplicate: 1,
      milestoneStatus: null,
      taskStatus: null,
      participationDivision: "00",
      attendanceDivision: "00",

      customers: [],
      productTradings: [
        {
          productTradingId: 4446,
          productId: 31,
          productName: "商品名3",
        },
      ],
      businessCards: [
        {
          businessCardId: 33356,
          businessCardName: "名刺名1",
        },
      ],
    },
    {
      itemType: 3,
      itemId: 123456,
      itemName: "Schedule Name3",
      employeeId: 332,
      startDate: "2020-06-12T23:59:59Z",
      endDate: "2020-06-13T23:59:59Z",
      itemIcon: "\\image\\damphan.png",
      isFullDay: 1,
      isOverDay: 0,
      isRepeat: 0,
      scheduleRepeatId: null,
      scheduleTypeId: 1,
      isPublic: 0,
      isReportActivity: 1,
      isParticipantUser: 0,
      isDuplicate: 1,
      milestoneStatus: null,
      taskStatus: null,
      participationDivision: "00",
      attendanceDivision: "02",

      customers: [],
      productTradings: [
        {
          productTradingId: 4446,
          productId: 31,
          productName: "商品名3",
        },
      ],
      businessCards: [
        {
          businessCardId: 33356,
          businessCardName: "名刺名1",
        },
      ],
    },
    {
      itemType: 3,
      itemId: 123456,
      itemName: "Schedule Name3",
      employeeId: 332,
      startDate: "2020-06-12T23:59:59Z",
      endDate: "2020-06-13T23:59:59Z",
      itemIcon: "\\image\\damphan.png",
      isFullDay: 1,
      isOverDay: 0,
      isRepeat: 0,
      scheduleRepeatId: null,
      scheduleTypeId: 1,
      isPublic: 0,
      isReportActivity: 1,
      isParticipantUser: 0,
      isDuplicate: 1,
      milestoneStatus: null,
      taskStatus: null,
      participationDivision: "00",
      attendanceDivision: "01",

      customers: [],
      productTradings: [
        {
          productTradingId: 4446,
          productId: 31,
          productName: "商品名3",
        },
      ],
      businessCards: [
        {
          businessCardId: 33356,
          businessCardName: "名刺名1",
        },
      ],
    },
    {
      itemType: 3,
      itemId: 123456,
      itemName: "Schedule Name3",
      employeeId: 332,
      startDate: "2020-06-12T23:59:59Z",
      endDate: "2020-06-13T23:59:59Z",
      itemIcon: "\\image\\damphan.png",
      isFullDay: 1,
      isOverDay: 0,
      isRepeat: 0,
      scheduleRepeatId: null,
      scheduleTypeId: 1,
      isPublic: 0,
      isReportActivity: 1,
      isParticipantUser: 0,
      isDuplicate: 1,
      milestoneStatus: null,
      taskStatus: null,
      participationDivision: "01",
      attendanceDivision: "00",

      customers: [],
      productTradings: [
        {
          productTradingId: 4446,
          productId: 31,
          productName: "商品名3",
        },
      ],
      businessCards: [
        {
          businessCardId: 33356,
          businessCardName: "名刺名1",
        },
      ],
    },
  ],
  countSchedule: 1,
};

export const DUMMY_CALENDAR_DAY = [
  {
    itemType: 2,
    itemId: 22209,
    itemName: "Task Name1",
    employeeId: 2221,
    startDate: "2018-09-07 00:30:00",
    endDate: "2018-09-07 01:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "00",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "Task Name1",
    employeeId: 2221,
    startDate: "2018-09-07 00:30:00",
    endDate: "2018-09-07 02:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "01",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "Task Name1",
    employeeId: 2221,
    startDate: "2018-09-07 03:00:00",
    endDate: "2018-09-07 04:00:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "02",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "Task Name1",
    employeeId: 2221,
    startDate: "2018-09-07 03:00:00",
    endDate: "2018-09-07 05:00:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 1,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "00",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "Task Name2",
    employeeId: 2221,
    startDate: "2018-09-07 06:00:00",
    endDate: "2018-09-07 07:00:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 1,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "01",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "Task Name3",
    employeeId: 2221,
    startDate: "2018-09-07 08:00:00",
    endDate: "2018-09-07 09:00:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 1,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "02",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "Task Name4",
    employeeId: 2221,
    startDate: "2018-09-07 13:00:00",
    endDate: "2018-09-07 14:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 1,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "02",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
];
export const dummyChooseDay = {
  dayname: "火",
  day: 4,
  holiday: "赤口",
};
export const dummyDataOverday = [
  {
    itemType: 2,
    itemId: 22209,
    itemName: "今日",
    employeeId: 2221,
    startDate: "2018-09-07 00:30:00",
    endDate: "2018-09-07 01:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "00",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "今日",
    employeeId: 2221,
    startDate: "2018-09-07 00:30:00",
    endDate: "2018-09-07 01:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "00",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "今日",
    employeeId: 2221,
    startDate: "2018-09-07 00:30:00",
    endDate: "2018-09-07 01:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "00",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "今日",
    employeeId: 2221,
    startDate: "2018-09-07 00:30:00",
    endDate: "2018-09-07 01:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "00",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
  {
    itemType: 2,
    itemId: 22209,
    itemName: "今日",
    employeeId: 2221,
    startDate: "2018-09-07 00:30:00",
    endDate: "2018-09-07 01:30:00",
    itemIcon: null,
    isFullDay: 1,
    isOverDay: 1,
    isRepeat: null,
    scheduleRepeatId: null,
    scheduleTypeId: null,
    isPublic: 0,
    isReportActivity: null,
    isParticipantUser: 0,
    isDuplicate: null,
    milestoneStatus: null,
    taskStatus: "00",
    participationDivision: null,
    attendanceDivision: null,
    customers: [],
    productTradings: [],
    businessCards: [],
  },
];
