import { StyleSheet } from "react-native";
import { theme } from "../../../config/constants";

export const styles = StyleSheet.create({
  container: { flex: 1, marginTop: 8 },
  containerSchedule: {
    backgroundColor: "white",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },
  containerScheduleJoined: {
    backgroundColor: "#ADE4C9",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },
  containerScheduleShare: {
    backgroundColor: "white",
    borderStyle: "dashed",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },

  containerItem: {
    backgroundColor: "#DEC6C6",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },
  containerItemComplete: {
    backgroundColor: "#E3E3E3",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },
  containerItemOvertime: {
    backgroundColor: "#EAFFD0",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },
  txtMilestone: { marginLeft: theme.space[1] },
  txtMilestoneOvertime: { marginLeft: theme.space[1], color: "red" },
  sizeIcon: { width: theme.space[4], height: theme.space[3] },
  textAbsent: { textDecorationLine: "line-through" },
  containerRenderDay: {
    width: "20%",
    justifyContent: "center",
    alignItems: "center",
  },
  headerCalendar: {
    flexDirection: "row",
    margin: theme.space[4],
    alignItems: "center",
  },
  viewRow: { flexDirection: "row", alignItems: "center" },
  btnScrollToDay: {
    height: theme.space[10],
    width: "30%",
    borderWidth: 1,
    borderColor: theme.colors.gray,
    borderRadius: theme.space[3],
    justifyContent: "center",
    alignItems: "center",
  },
  boxListGroup: {
    position: "absolute",
    top: 64,
    height: 68,
    right: 100,
    width: "35%",
    backgroundColor: theme.colors.white,
    borderRadius: theme.space[2],
    borderColor: theme.colors.gray200,
    borderWidth: 1,
    zIndex: 90,
    shadowColor: theme.colors.gray200,
    shadowOffset: {
      width: 3,
      height: 12,
    },
    shadowOpacity: 1,
    shadowRadius: 16.0,
    paddingVertical: theme.space[1],
    elevation: 24,
  },
  boxGroup: {
    borderColor: theme.colors.gray,
    borderRadius: theme.space[3],
    borderWidth: 1,
    flexDirection: "row",
    width: "50%",

    margin: theme.space[2],
    alignItems: "center",
    justifyContent: "center",
    padding: theme.space[1],
    zIndex: 6,
    position: "relative",
    height: theme.space[10],
  },
  txtGroup: {
    fontSize: theme.fontSizes[3],
    paddingLeft: theme.space[3],
    paddingRight: theme.space[5],
    color: theme.colors.gray1,
    flex: 1,
  },
  txtBlue: {
    fontSize: theme.fontSizes[3],
    paddingLeft: theme.space[3],
    paddingRight: theme.space[5],
    color: theme.colors.blue200,
    flex: 1,
  },
  groupSelectedView: {
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    backgroundColor: theme.colors.blue,
  },
  boxEmployeeInfo: {
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    // zIndex: 99,
  },
  txtColor: { color: theme.colors.gray1 },
  groupBtnHeader: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "flex-end",
  },
  itemDay: {
    height: 40,
    width: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  txtDayNumber: { fontSize: 18 },
  viewDay: { justifyContent: "flex-start" },
  txtDayName: { fontSize: 10 },
  perpetualCalendar: { fontSize: 10 },
  viewRenderDay: {
    borderBottomWidth: 1,
    flex: 1,
    borderBottomColor: "#E5E5E5",
    alignItems: "center",
    flexDirection: "row",
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#AFE6CB",
    marginRight: 10,
  },
});
export const styleCalendarDay = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  containerSchedule: {
    backgroundColor: "white",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },
  containerScheduleJoined: {
    backgroundColor: "#ADE4C9",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[1],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },
  containerScheduleShare: {
    backgroundColor: "white",
    borderStyle: "dashed",
    borderRadius: theme.space[2],
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[2],
    borderWidth: 1,
    borderColor: "#ADE4C9",
    justifyContent: "center",
  },

  containerItem: {
    position: "absolute",
    backgroundColor: "#ADE4C9",
    borderRadius: 5,
    paddingLeft: 4,
    minHeight: 25,
    flex: 1,
    paddingTop: 5,
    paddingBottom: 0,
    flexDirection: "column",
    alignItems: "flex-start",
    overflow: "hidden",
  },
  containerItemComplete: {
    position: "absolute",
    backgroundColor: "#E3E3E3",
    borderColor: "#ADE4C9",
    borderWidth: 1,
    borderRadius: 5,
    paddingLeft: 4,
    minHeight: 25,
    flex: 1,
    paddingTop: 5,
    paddingBottom: 0,
    flexDirection: "column",
    alignItems: "flex-start",
    overflow: "hidden",
  },
  containerItemOvertime: {
    position: "absolute",
    backgroundColor: "#EAFFD0",
    borderColor: "#ADE4C9",
    borderWidth: 1,
    borderRadius: 5,
    paddingLeft: 4,
    minHeight: 25,
    flex: 1,
    paddingTop: 5,
    paddingBottom: 0,
    flexDirection: "column",
    alignItems: "flex-start",
    overflow: "hidden",
  },
  txtMilestone: { marginLeft: theme.space[1] },
  txtMilestoneOvertime: { marginLeft: theme.space[1], color: "red" },
  sizeIcon: { width: theme.space[4], height: theme.space[3] },
  textAbsent: { textDecorationLine: "line-through" },
  viewRow: { flexDirection: "row", alignItems: "center" },
  textStyle: { color: theme.colors.gray1 },
  viewDayLeft: { flexDirection: "row", width: "100%", alignItems: "center" },
  containerDayLeft: {
    alignItems: "center",
    width: 49,
    height: "100%",
  },
  viewEventAllDay: { flex: 1, paddingLeft: theme.space[2] },
  viewOtherItemOverDay: {
    padding: 10,
    marginRight: 10,
    marginTop: theme.space[1],
    justifyContent: "center",
  },
  btnIconChangeArr: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  contentDayLeft: { alignItems: "center", flex: 1, justifyContent: "center" },
});
