import { StyleSheet } from "react-native";

export const OptionsStyles = StyleSheet.create({
  container: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: "#E3E3E3",
    paddingHorizontal: "3%",
  },
  containerComment: { width: "100%" },
  btn: { flex: 1, alignItems: "center", justifyContent: "center" },
  btnIcon: { width: 13, height: 13 },
  topContent: {
    flexDirection: "row",
    width: "100%",
    height: 35,
  },
  topContentInfo: {
    flex: 5,
    flexDirection: "row",
    alignItems: "center",
  },
  topContentInfoImg: { width: 25, height: 25, borderRadius: 15 },
  topContentInfoName: { fontSize: 15, marginLeft: 10, color: "#0F6DB1" },
  topContentDate: {
    flex: 3,
    alignItems: "flex-end",
    paddingTop: 4,
  },
  topContentInfoDate: { fontSize: 10, color: "#959595" },
  topContentDelete: {
    flex: 1,
    alignItems: "center",
  },
  topContentInfoDelete: { width: 18, height: 30 },
  mainContent: { width: "100%", marginTop: 10, paddingLeft: "8%" },
  containerAddress: { flexDirection: "row" },
  address: { color: "#333333", fontSize: 14 },
  addressName: {
    color: "#0F6DB2",
    fontSize: 14,
    marginLeft: 6,
    marginBottom: 6,
  },
  mainTxt: { letterSpacing: 1, fontSize: 14, lineHeight: 20 },
  mainBtn: {
    width: 120,
    height: 28,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E4E4E4",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
  },
  mainBtnTxt: {
    color: "#666666",
    fontSize: 14,
  },
  btnReaction: {
    borderColor: "#E3E3E3",
    borderRadius: 8,
    borderWidth: 1,
    width: 48,
    height: 28,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  btnReactionTxt: {
    fontSize: 12,
    marginHorizontal: 1,
    color: "#666666",
  },
  btnReactionIcon: {
    fontSize: 14,
    marginHorizontal: 1,
  },
  containerReaction: { width: "100%", marginTop: 10 },
  containerOptions: {
    flexDirection: "row",
    height: 60,
    width: "100%",
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: "#E3E3E3",
  },
  btnShowPast: {
    width: 160,
    height: 35,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E4E4E4",
    alignItems: "flex-start",
    justifyContent: "center",
    paddingLeft: 10,
    marginLeft: "8%",
  },
  btnShowPastTxt: { color: "#666666", fontSize: 14 },
  containerOptionsComment: {
    width: "100%",
    flexDirection: "row",
    height: 55,
    marginVertical: 6,
  },
  containerReply: { width: "90%", marginLeft: "10%", marginTop: 10 },
  containerReplyOption: {
    flexDirection: "row",
    width: "104%",
    height: 40,
    marginLeft: "-7%",
  },
});
