export const GLOBAL_DEF = {
  EXTENSION_BELONG_LIST: 1
};

export const STATUS_MILESTONE = {
  TODO: 0,
  FINISH: 1
};

export const STATUS_MILESTONE_FIX = {
  TODO: 1,
  WORKING: 2,
  FINISH: 3
};

export const TIMEOUT_TOAST_MESSAGE = 2000;

export const MILESTONE_UPDATE_FLG = {
  TODO: 1,
  COMPLETE: 2
};

export const TYPE_GLOBAL_CONTROL = {
  LIST: 0,
  TASK: 1
};
export const STATUS_DATA = {
  TODO: 1,
  FINISHED: 2
};

export const TYPE_EVENT_MOUSE_ENTER = {
  CUSTOMER_PRODUCT_TRADING: 'CUSTOMER_PRODUCT_TRADING',
  TASK_NAME: 'TASK_NAME',
  TASK_FILE: 'TASK_FILE',
  TASK_MEMO: 'TASK_MEMO',
  TASK_OPERATOR: 'TASK_OPERATOR',
  TASK_MILESTONE_NAME: 'TASK_MILESTONE_NAME',
  SUB_TASK: 'SUB_TASK',
  MILESTONE_NAME: 'MILESTONE_NAME',
  MILESTONE_TASK: 'MILESTONE_TASK'
};

export const SIZE_TOOL_TIP = {
  HEIGHT_OPERATOR: 240,
  MAX_HEIGHT_OTHER: 350
};

export const LICENSE = {
  CUSTOMER_LICENSE: 5,
  SALES_LICENSE: 16
};
