export const DUMMY_DATA_GET_BUSINESS_CARDS = {
  businessCards: [
    {
      businessCardId: 1,
      customerId: 1,
      customerName: "string",
      alternativeCustomerName: "string",
      firstName: "名刺氏名",
      lastName: "string",
      firstNameKana: "string",
      lastNameKana: "string",
      position: "string",
      departmentName: "string",
      zipCode: "string",
      prefecture: "string",
      addressUnderPrefecture: "string",
      building: "string",
      address: "string",
      emailAddress: "string",
      phoneNumber: 1,
      mobileNumber: 1,
      lastContactDate: "2019/02/15 10:20:12",
      isWorking: 1,
      memo: "string",
      businessCardImagePath:
        "https://i.pinimg.com/originals/80/1f/b5/801fb51609d2ea363f9c1d89af96d04e.jpg",
      businessCardImageName: "businessCardImage",
      businessCardsReceives: [
        {
          employeeId: 123,
          receiveDate: "2019/02/22 09:30:00",
          lastContactDateReceiver: "2019/02/25 10:20:12",
        },
        {
          employeeId: 124,
          receiveDate: "2019/02/12 09:30:00",
          lastContactDateReceiver: "2019/02/15 10:20:12",
        },
      ],
      saveMode: false,
    },
    {
      businessCardId: 2,
      customerId: 2,
      customerName: "string",
      alternativeCustomerName: "string",
      firstName: "名刺氏名",
      lastName: "string",
      firstNameKana: "string",
      lastNameKana: "string",
      position: "string",
      departmentName: "string",
      zipCode: "string",
      prefecture: "string",
      addressUnderPrefecture: "string",
      building: "string",
      address: "string",
      emailAddress: "string",
      phoneNumber: 2,
      mobileNumber: 2,
      lastContactDate: "2019/02/15 10:20:12",
      isWorking: 2,
      memo: "string",
      businessCardImagePath:
        "https://vietandesign.com/upload/application/admin/image/in%20offset/card%20visit/thiet-ke-card-visit-viet-an-design-1.jpg",
      businessCardImageName: "businessCardImage",
      businessCardsReceives: [
        {
          employeeId: 123,
          receiveDate: "2019/02/22 09:30:00",
          lastContactDateReceiver: "2019/02/25 10:20:12",
        },
        {
          employeeId: 124,
          receiveDate: "2019/02/12 09:30:00",
          lastContactDateReceiver: "2019/02/15 10:20:12",
        },
      ],
      saveMode: false,
    },
    {
      businessCardId: 3,
      customerId: 3,
      customerName: "string",
      alternativeCustomerName: "string",
      firstName: "名刺氏名",
      lastName: "string",
      firstNameKana: "string",
      lastNameKana: "string",
      position: "string",
      departmentName: "string",
      zipCode: "string",
      prefecture: "string",
      addressUnderPrefecture: "string",
      building: "string",
      address: "string",
      emailAddress: "string",
      phoneNumber: 2,
      mobileNumber: 2,
      lastContactDate: "2019/02/15 10:20:12",
      isWorking: 2,
      memo: "string",
      businessCardImagePath:
        "https://vietandesign.com/upload/application/admin/image/in%20offset/card%20visit/thiet-ke-card-visit-viet-an-design-1.jpg",
      businessCardImageName: "businessCardImage",
      businessCardsReceives: [
        {
          employeeId: 123,
          receiveDate: "2019/02/22 09:30:00",
          lastContactDateReceiver: "2019/02/25 10:20:12",
        },
        {
          employeeId: 124,
          receiveDate: "2019/02/12 09:30:00",
          lastContactDateReceiver: "2019/02/15 10:20:12",
        },
      ],
      saveMode: true,
    },
  ],
  totalRecords: 3,
  fieldInfo: [
    {
      fieldId: 1,
      fieldName: "businessCardId",
    },
  ],
  lastUpdateDate: "2019/02/12 09:30:00",
  initializeInfo: {
    selectedTargetType: 1,
    selectedTargetId: 1,
  },
};

export const dataGetBusinessCardListDummy = {
  data: {
    listInfo: [
      {
        listName: "shareList1",
        listId: 3001,
        displayOrder: 2,
        listType: 2,
        employeeId: 1,
        listMode: 1,
        ownerList: [1],
        viewerList: [],
        displayOrderFavoriteList: 1,
      },
      {
        listName: "shareList2",
        listId: 3002,
        displayOrder: 3,
        listType: 1,
        employeeId: 1,
        listMode: 1,
        ownerList: [1],
        viewerList: [],
        displayOrderFavoriteList: 2,
      },
      {
        listName: "shareList3",
        listId: 3003,
        displayOrder: 3,
        listType: 1,
        employeeId: 1,
        listMode: 2,
        ownerList: [1],
        viewerList: [],
        displayOrderFavoriteList: 3,
      },
      {
        listName: "shareList4",
        listId: 3004,
        displayOrder: 4,
        listType: 1,
        employeeId: 1,
        listMode: 2,
        ownerList: [1],
        viewerList: [],
      },
    ],
  },
};

export const dataCreateBusinessCardsListDummy = {
  data: {
    businessCardListDetailId: 10002,
  },
};
