cd `dirname $0` || exit 1
. ./args.conf
if [[ $CLOUDFRONT_API_ENABLE == "true" ]]; then
    case $AWS_ACCOUNT_ID in
    267458812797 ) APIGATEWAY_ADDRESS=https://api.insightwatch.io ;;
    749077664194 ) APIGATEWAY_ADDRESS=https://api.stg.insightwatch.io ;;
    216054658829 ) APIGATEWAY_ADDRESS=https://api.dev.insightwatch.io ;;
    esac
fi
echo "CLOUDFRONT_API_ENABLE="$CLOUDFRONT_API_ENABLE
echo "APIGATEWAY_ADDRESS="$APIGATEWAY_ADDRESS
COMMIT_TAG=${RELEASE_TAG:-$CODEBUILD_RESOLVED_SOURCE_VERSION}
export APIGATEWAY_ADDRESS=$APIGATEWAY_ADDRESS
export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
export COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
export S3_CFNTEMPLATE_BUCKET_URL=$S3_CFNTEMPLATE_BUCKET_URL
export COMMIT_TAG=$COMMIT_TAG
npm run build
