Description: Premembers S3 Access Log Bucket
Parameters:
  Env:
    Description: 'Choose the environment to create: ''Dev'' or ''Stg'' or''Prd'''
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - stg
    - prd
  ServiceName:
    Description: Name for the service
    Type: String
    Default: premembers
    AllowedPattern: "[-_ a-z0-9]*"
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes
      and underscores.
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "LogDeliveryWrite"
      BucketName: 
        Fn::Join:
          - "-"
          - - Ref: ServiceName 
            - Ref: Env
            - 's3'
            - 'access'
            - 'log'
      Tags:
      - Key: Service
        Value:
          Ref: ServiceName
      - Key: Env
        Value:
          Ref: Env
    DeletionPolicy: Retain