export const DUMMY_ACTIVITY_LIST_RESPONSE = {
  activities: [
    {
      activityId: 1,
      contactDate: '2019/07/05',
      activityStartTime: '2019/07/05 10:00',
      activityEndTime: '2019/07/05 11:00',
      activityDuration: 60,
      employee: {
        employeeName: 'EMP NAME',
        employeeId: 1,
        employeePhoto: 'http://placehold.jp/50x50.png'
      },
      businessCards: [
        {
          customerName: 'customerName 1',
          businessCardId: 1,
          firstName: '直樹1 1111',
          lastName: '直樹1',
          firstNameKana: 'タナカ',
          lastNameKana: 'タナカ',
          position: null,
          departmentName: '直樹',
          businessCardImagePath: 'http://placehold.jp/60x60.png',
          businessCardImageName: 'businessCardImageName 1'
        },
        {
          customerName: 'customerName 2',
          businessCardId: 2,
          firstName: '直樹2',
          lastName: '直樹2',
          firstNameKana: 'タナカ2',
          lastNameKana: 'タナカ2',
          position: null,
          departmentName: '直樹2',
          businessCardImagePath: 'http://placehold.jp/60x60.png',
          businessCardImageName: 'businessCardImageName 2'
        }
      ],
      interviewers: ['タナカ'],
      customer: {
        customerId: 1,
        customerName: 'Customer name'
      },
      productTradings: [
        {
          productTradingId: 1,
          customerName: "customerName 1",
          productId: 1,
          productName: '商品A',
          productImagePath: 'http://placehold.jp/60x60.png',
          productImageName: 'productImageName 1',
          quantity: 20,
          price: 20,
          amount: 20,
          productTradingProgressId: 1,
          progressName: '進捗名A',
          endPlanDate: '2019/07/05 10:00',
          orderPlanDate: '2019/07/05 11:00',
          employee: {
            employeeId: 1,
            employeeName: 'employeeName 1',
            employeeSurname: 'employeeSurname 1',
            employeePhoto: {
              filePath: 'http://placehold.jp/30x30.png',
              fileName: 'employeePhoto-fileName 1'
            }
          },
          memo: 'Memo 1'
        },
        {
          productTradingId: 2,
          customerName: "customerName 2",
          productId: 2,
          productName: '商品B',
          productImagePath: 'http://placehold.jp/60x60.png',
          productImageName: 'productImageName 2',
          quantity: 20,
          price: 20,
          amount: 20,
          productTradingProgressId: 2,
          progressName: '進捗名B',
          endPlanDate: '2019/07/05 10:00',
          orderPlanDate: '2019/07/05 11:00',
          employee: {
            employeeId: 2,
            employeeName: 'employeeName 2',
            employeeSurname: 'employeeSurname 2',
            employeePhoto: {
              filePath: 'http://placehold.jp/30x30.png',
              fileName: 'employeePhoto-fileName 2'
            }
          },
          memo: 'Memo 1'
        },
      ],
      customers: [
        {
          customerId: 1,
          customerName: 'Customer name 1'
        },
        {
          customerId: 2,
          customerName: 'Customer name 2'
        },
      ],
      memo: 'MEMO',
      createdUser: {
        createdUserId: 1,
        createdDate: '2019/07/05 10:00',
        createdUserName: 'createdUserName'
      },
      updatedUser: {
        updatedUserId: 2,
        updatedUserName: 'updatedUserName',
        updatedDate: '2019/07/05'
      },
      extTimeline: null,
      task: null,
      schedule: {
        scheduleId: 1,
        scheduleName: 'scheduleName'
      },
      milestone: null,
      nextSchedule: {
        nextScheduleDate: '2019/05/09',
        nextScheduleId: 1,
        nextScheduleName: '予定',
        iconPath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT8mif2MbxBbtR_E13NsGUr25pI3tHC_jex36gZZ621ureNxooo&usqp=CAU',
        customerName: '直樹',
        productTradings: [
          {
            productTradingName: '商品1'
          },
          {
            productTradingName: '商品2'
          }
        ]
      },
      initializeInfo: null,
      total: 10
    },
    {
      activityId: 2,
      contactDate: '2019/07/05',
      activityStartTime: '2019/07/05 10:00',
      activityEndTime: '2019/07/05 11:00',
      activityDuration: 60,
      employee: {
        employeeName: 'EMP NAME',
        employeeId: 1,
        employeePhoto: 'http://placehold.jp/50x50.png'
      },
      businessCards: [
        {
          businessCardId: 1,
          firstName: '直樹1',
          lastName: '直樹1',
          firstNameKana: 'タナカ',
          lastNameKana: 'タナカ',
          position: null,
          departmentName: '直樹'
        },
        {
          businessCardId: 2,
          firstName: '直樹2',
          lastName: '直樹2',
          firstNameKana: 'タナカ2',
          lastNameKana: 'タナカ2',
          position: null,
          departmentName: '直樹2'
        }
      ],
      interviewers: ['タナカ'],
      customer: {
        customerId: 1,
        customerName: 'Customer name'
      },
      productTradings: [
        {
          productTradingId: 1,
          productId: 1,
          productName: '商品C',
          quantity: 20,
          price: 20,
          amount: 20,
          productTradingProgressId: 1,
          productTradingProgressName: '進捗名C',
          endPlanDate: '2019/07/05 10:00',
          orderPlanDate: '2019/07/05 11:00',
          employeeId: 2,
          employeeName: 'employee Name 1',
          employeePhoto: 'http://placehold.jp/30x30.png',
          memo: 'Memo 1'
        },
        {
          productTradingId: 2,
          productId: 2,
          productName: '商品D',
          quantity: 20,
          price: 20,
          amount: 20,
          productTradingProgressId: 2,
          productTradingProgressName: '進捗名D',
          endPlanDate: '2019/07/05 10:00',
          orderPlanDate: '2019/07/05 11:00',
          employeeId: 1,
          employeeName: 'employee Name 2',
          employeePhoto: 'http://placehold.jp/30x30.png',
          memo: 'Memo 2'
        }
      ],
      customers: [
        {
          customerId: 1,
          customerName: 'Customer name 1'
        },
        {
          customerId: 2,
          customerName: 'Customer name 2'
        },
      ],
      memo: 'MEMO',
      createdUser: {
        createdUserId: 1,
        createdDate: '2019/07/05',
        createdUserName: 'createdUserName',
        createdUserPhoto: ''
      },
      updatedUser: {
        updatedUserId: 2,
        updatedUserName: 'updatedUserName',
        updatedDate: '2019/07/05',
        updatedUserPhoto: ''
      },
      extTimeline: null,
      task: {
        taskId: 1,
        taskName: 'taskName'
      },
      schedule: null,
      milestone: null,
      nextSchedule: {
        nextScheduleDate: '2019/05/09',
        nextScheduleId: 1,
        nextScheduleName: 'nextScheduleName',
        iconPath: 'iconPath',
        customerName: 'customerName',
        productTradings: [
          {
            productTradingName: 'productTradingName'
          }
        ]
      },
      initializeInfo: null,
      total: 10
    },
  ],
}

export const DUMMY_ACTIVITY_DETAIL = {
  data: {
    activities: {
      activityId: 1,
      contactDate: "2014-07-20T17:00:00Z",
      activityStartTime: "2014-07-21T02:35:00Z",
      activityEndTime: "2014-07-21T10:35:00Z",
      activityDuration: 60,
      activityFormatId: 1,
      name:  "{\"ja_jp\": \"FORMAT_1\"}",
      activityFormats: [
          {
              createdDate: "2020-07-15T06:20:11.473938Z",
              createdUser: 1,
              updatedDate: "2020-07-16T08:33:59.376574Z",
              updatedUser: 1,
              activityFormatId: 1,
              displayOrder: 1,
              name: "{\"ja_jp\": \"FORMAT_1\"}",
              fieldUse: "{\"83\": 1, \"84\": 1, \"85\": 1, \"86\": 1, \"87\": 1, \"88\": 1, \"89\": 1, \"90\": 1, \"91\": 1, \"92\": 1, \"93\": 1, \"94\": 0, \"95\": 1, \"96\": 1, \"97\": 1, \"98\": 1, \"99\": 1, \"194\": 0, \"195\": 1, \"205\": 1, \"206\": 1, \"207\": 1, \"208\": 1, \"209\": 1}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: false
          },
          {
              createdDate: "2020-07-15T06:20:11.476299Z",
              createdUser: 1,
              updatedDate: "2020-07-16T08:34:10.077447Z",
              updatedUser: 1,
              activityFormatId: 2,
              displayOrder: 2,
              name: "{\"ja_jp\": \"FORMAT_2\"}",
              fieldUse: "{\"83\": 1, \"84\": 1, \"85\": 1, \"86\": 1, \"87\": 1, \"88\": 1, \"89\": 1, \"90\": 1, \"91\": 1, \"92\": 1, \"93\": 1, \"94\": 1, \"95\": 1, \"96\": 1, \"97\": 1, \"98\": 1, \"99\": 1, \"194\": 0, \"195\": 1, \"205\": 1, \"206\": 1, \"207\": 0, \"208\": 1, \"209\": 0}",
              productTradingFieldUse: "{\"170\": 1, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: false
          },
          {
              createdDate: "2020-07-15T06:20:11.477947Z",
              createdUser: 1,
              updatedDate: "2020-07-16T08:34:10.077447Z",
              updatedUser: 1,
              activityFormatId: 6,
              displayOrder: 4,
              name: "{\"en_us\": \"\", \"ja_jp\": \"format_3\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 1, \"84\": 1, \"85\": 1, \"86\": 1, \"87\": 1, \"88\": 1, \"89\": 1, \"90\": 1, \"91\": 1, \"92\": 1, \"93\": 1, \"94\": 1, \"95\": 1, \"96\": 0, \"97\": 1, \"98\": 1, \"99\": 1, \"194\": 1, \"195\": 1, \"205\": 1, \"206\": 1, \"207\": 1, \"208\": 1, \"209\": 1}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 1, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.479611Z",
              createdUser: 1,
              updatedDate: "2020-07-16T08:34:10.077447Z",
              updatedUser: 1,
              activityFormatId: 7,
              displayOrder: 5,
              name: "{\"en_us\": \"\", \"ja_jp\": \"format_4\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 0, \"84\": 1, \"85\": 0, \"86\": 1, \"87\": 0, \"88\": 1, \"89\": 0, \"90\": 0, \"91\": 0, \"92\": 0, \"93\": 0, \"94\": 1, \"95\": 0, \"96\": 0, \"97\": 1, \"98\": 1, \"99\": 1, \"194\": 0, \"195\": 0, \"205\": 1, \"206\": 0, \"207\": 1, \"208\": 0, \"209\": 1}",
              productTradingFieldUse: "{\"170\": 1, \"171\": 1, \"172\": 0, \"173\": 1, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.481217Z",
              createdUser: 1,
              updatedDate: "2020-07-16T03:55:51.506021Z",
              updatedUser: 1,
              activityFormatId: 39,
              displayOrder: 6,
              name: "{\"en_us\": \"\", \"ja_jp\": \"format_5\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 0, \"84\": 1, \"85\": 1, \"86\": 0, \"87\": 1, \"88\": 1, \"89\": 0, \"90\": 0, \"91\": 0, \"92\": 0, \"93\": 0, \"94\": 1, \"95\": 0, \"96\": 0, \"97\": 1, \"98\": 1, \"99\": 1, \"194\": 1, \"195\": 1, \"205\": 0, \"206\": 1, \"207\": 0, \"208\": 1, \"209\": 0}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 1, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.482865Z",
              createdUser: 1,
              updatedDate: "2020-07-16T03:46:59.422020Z",
              updatedUser: 1,
              activityFormatId: 40,
              displayOrder: 7,
              name: "{\"en_us\": \"\", \"ja_jp\": \"format_6\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 1, \"84\": 1, \"85\": 1, \"86\": 1, \"87\": 0, \"88\": 1, \"89\": 0, \"90\": 1, \"91\": 0, \"92\": 1, \"93\": 0, \"94\": 1, \"95\": 0, \"96\": 0, \"97\": 1, \"98\": 0, \"99\": 0, \"194\": 1, \"195\": 1, \"205\": 1, \"206\": 0, \"207\": 1, \"208\": 0, \"209\": 1}",
              productTradingFieldUse: "{\"170\": 1, \"171\": 0, \"172\": 0, \"173\": 1, \"174\": 1, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.484420Z",
              createdUser: 1,
              updatedDate: "2020-07-16T08:33:59.376574Z",
              updatedUser: 1,
              activityFormatId: 53,
              displayOrder: 8,
              name: "{\"en_us\": \"\", \"ja_jp\": \"format_7\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 1, \"84\": 1, \"85\": 1, \"86\": 0, \"87\": 1, \"88\": 1, \"89\": 1, \"90\": 0, \"91\": 1, \"92\": 0, \"93\": 0, \"94\": 1, \"95\": 0, \"96\": 1, \"97\": 0, \"98\": 1, \"99\": 1, \"194\": 0, \"195\": 1, \"205\": 0, \"206\": 1, \"207\": 0, \"208\": 1, \"209\": 0}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.486016Z",
              createdUser: 1,
              updatedDate: "2020-07-15T16:58:57.004741Z",
              updatedUser: 1,
              activityFormatId: 91,
              displayOrder: 9,
              name: "{\"en_us\": \"\", \"ja_jp\": \"col1\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 1, \"84\": 1, \"85\": 0, \"86\": 0, \"87\": 0, \"88\": 1, \"89\": 0, \"90\": 0, \"91\": 0, \"92\": 0, \"93\": 0, \"94\": 1, \"95\": 0, \"96\": 0, \"97\": 0, \"98\": 1, \"99\": 1, \"194\": 0, \"195\": 1, \"205\": 0, \"206\": 0, \"207\": 0, \"208\": 0, \"209\": 0}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 1, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.487625Z",
              createdUser: 1,
              updatedDate: "2020-07-15T13:52:19.357655Z",
              updatedUser: 1,
              activityFormatId: 92,
              displayOrder: 10,
              name: "{\"en_us\": \"\", \"ja_jp\": \"col2\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 0, \"84\": 1, \"85\": 0, \"86\": 0, \"87\": 0, \"88\": 1, \"89\": 1, \"90\": 0, \"91\": 0, \"92\": 0, \"93\": 0, \"94\": 1, \"95\": 0, \"96\": 0, \"97\": 0, \"98\": 0, \"99\": 1, \"194\": 1, \"195\": 0, \"205\": 0, \"206\": 0, \"207\": 0, \"208\": 0, \"209\": 0}",
              productTradingFieldUse: "{\"170\": 1, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 1, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.489731Z",
              createdUser: 1,
              updatedDate: "2020-07-15T14:07:31.992032Z",
              updatedUser: 1,
              activityFormatId: 93,
              displayOrder: 11,
              name: "{\"en_us\": \"FORMAT NAME US\", \"ja_jp\": \"FORMAT NAME JP\", \"zh_cn\": \"FORMAT NAME CN\"}",
              fieldUse: "{\"83\": 0, \"84\": 1, \"85\": 0, \"86\": 0, \"87\": 0, \"88\": 0, \"89\": 0, \"90\": 0, \"92\": 0, \"94\": 1, \"95\": 0, \"96\": 0, \"97\": 0, \"98\": 1, \"99\": 1, \"194\": 0, \"195\": 0}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 1, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.491350Z",
              createdUser: 1,
              updatedDate: "2020-07-15T13:35:58.788409Z",
              updatedUser: 1,
              activityFormatId: 94,
              displayOrder: 12,
              name: "{\"en_us\": \"\", \"ja_jp\": \"new\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 0, \"84\": 0, \"85\": 0, \"86\": 0, \"87\": 0, \"88\": 0, \"89\": 0, \"90\": 0, \"92\": 0, \"94\": 0, \"95\": 0, \"96\": 0, \"97\": 0, \"98\": 1, \"99\": 0, \"194\": 0, \"195\": 0}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.493022Z",
              createdUser: 1,
              updatedDate: "2020-07-15T06:20:11.493022Z",
              updatedUser: 1,
              activityFormatId: 95,
              displayOrder: 13,
              name: "{\"en_us\": \"\", \"ja_jp\": \"new\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 0, \"84\": 0, \"85\": 0, \"86\": 0, \"87\": 0, \"88\": 0, \"89\": 0, \"90\": 0, \"92\": 0, \"94\": 0, \"95\": 0, \"96\": 0, \"97\": 0, \"98\": 0, \"99\": 0, \"194\": 0, \"195\": 0}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          },
          {
              createdDate: "2020-07-15T06:20:11.494996Z",
              createdUser: 1,
              updatedDate: "2020-07-15T06:20:11.494996Z",
              updatedUser: 1,
              activityFormatId: 96,
              displayOrder: 14,
              name: "{\"en_us\": \"\", \"ja_jp\": \"23423432\", \"zh_cn\": \"\"}",
              fieldUse: "{\"83\": 0, \"84\": 0, \"85\": 0, \"86\": 0, \"87\": 0, \"88\": 0, \"89\": 0, \"90\": 0, \"92\": 0, \"94\": 0, \"95\": 0, \"96\": 0, \"97\": 0, \"98\": 0, \"99\": 0, \"194\": 0, \"195\": 0}",
              productTradingFieldUse: "{\"170\": 0, \"171\": 0, \"172\": 0, \"173\": 0, \"174\": 0, \"175\": 0, \"176\": 0, \"177\": 0, \"178\": 0, \"179\": 0, \"180\": 0, \"181\": 0, \"182\": 0, \"183\": 0, \"184\": 0}",
              isAvailable: true
          }
      ],
      employee: {
          employeeId: 123,
          employeeName: null,
          employeePhoto: null,
          employeeSurname: null
      },
      businessCards: [
          {
              businessCardId: 2,
              customerName: null,
              firstName: null,
              lastName: null,
              firstNameKana: null,
              lastNameKana: null,
              position: null,
              departmentName: null,
              businessCardImagePath: null,
              businessCardImageName: null
          },
          {
              businessCardId: 3,
              customerName: null,
              firstName: null,
              lastName: null,
              firstNameKana: null,
              lastNameKana: null,
              position: null,
              departmentName: null,
              businessCardImagePath: null,
              businessCardImageName: null
          }
      ],
      interviewer: [
          "interviewers 1",
          "interviewers 2"
      ],
      customer: {
          customerId: 123,
          customerName: null,
          customerPhoto: null
      },
      productTradings: [
          {
              productTradingId: 2,
              customerId: 123,
              customerName: null,
              productId: 1,
              productName: "Product Name 1",
              productImagePath: null,
              productImageName: null,
              quantity: 1,
              price: 1.0,
              amount: 1,
              productTradingProgressId: null,
              progressName: null,
              endPlanDate: "2014-07-20T17:00:00Z",
              orderPlanDate: "2014-07-20T17:00:00Z",
              employee: {
                  employeeId: null,
                  employeeName: null,
                  employeePhoto: null,
                  employeeSurname: null
              },
              memo: "メモ メモ メモ メモ",
              productTradingData:  "{\"text_1\": \"Hello world\", \"pulldown_1\": 12}"
          },
          {
              productTradingId: 2,
              customerId: 123,
              customerName: null,
              productId: 1,
              productName: "Product Name 1",
              productImagePath: null,
              productImageName: null,
              quantity: 1,
              price: 1.0,
              amount: 1,
              productTradingProgressId: null,
              progressName: null,
              endPlanDate: "2014-07-20T17:00:00Z",
              orderPlanDate: "2014-07-20T17:00:00Z",
              employee: {
                  employeeId: null,
                  employeeName: null,
                  employeePhoto: null,
                  employeeSurname: null
              },
              memo: "メモ メモ メモ メモ",
              productTradingData: "{\"text_1\": \"Hello world\", \"pulldown_1\": 12}"
          },
          {
              productTradingId: 2,
              customerId: 123,
              customerName: null,
              productId: 1,
              productName: "Product Name 1",
              productImagePath: null,
              productImageName: null,
              quantity: 1,
              price: 1.0,
              amount: 1,
              productTradingProgressId: null,
              progressName: null,
              endPlanDate: "2014-07-20T17:00:00Z",
              orderPlanDate: "2014-07-20T17:00:00Z",
              employee: {
                  employeeId: null,
                  employeeName: null,
                  employeePhoto: null,
                  employeeSurname: null
              },
              memo: "メモ メモ メモ メモ",
              productTradingData: "{\"text_1\": \"Hello world\", \"pulldown_1\": 12}"
          },
          {
              productTradingId: 2,
              customerId: 123,
              customerName: null,
              productId: 1,
              productName: "Product Name 1",
              productImagePath: null,
              productImageName: null,
              quantity: 1,
              price: 1.0,
              amount: 1,
              productTradingProgressId: null,
              progressName: null,
              endPlanDate: "2014-07-20T17:00:00Z",
              orderPlanDate: "2014-07-20T17:00:00Z",
              employee: {
                  employeeId: null,
                  employeeName: null,
                  employeePhoto: null,
                  employeeSurname: null
              },
              memo: "メモ メモ メモ メモ",
              productTradingData: "{\"text_1\": \"Hello world\", \"pulldown_1\": 12}"
          }
      ],
      customerRelations: [
          {
              customerRelationId: 124,
              customerName: null,
              customerPhoto: null
          }
      ],
      memo: "メモ メモ メモ メモ",
      task: null,
      schedule: {
          scheduleId: 10,
          scheduleName: null,
          finishDate: null
      },
      milestone: null,
      nextSchedules: null,
      createdUser: {
          createdDate: "2020-07-15T06:29:22.468198Z",
          employeeName: "Admin1",
          employeeSurname: "Admin",
          employeePhoto: {
              fileName: "50x50.png",
              filePath: "\r\nhttp://placehold.jp/",
              fileUrl: null,
              status: null
          },
          employeeId: 1
      },
      updatedUser: {
          updatedDate: "2020-07-16T01:03:06.920576Z",
          employeeName: "Admin1",
          employeeSurname: "Admin",
          employeePhoto: {
              fileName: "50x50.png",
              filePath: "\r\nhttp://placehold.jp/",
              fileUrl: null,
              status: null
          },
          employeeId: 1
      },
      activityData: {}
  },
  fieldInfoActivity: [
      {
          fieldId: 96,
          fieldBelong: 6,
          fieldName: "created_date",
          fieldLabel: "{\"ja_jp\": \"登録日\"}",
          fieldType: 7,
          fieldOrder: 15,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 97,
          fieldBelong: 6,
          fieldName: "created_user",
          fieldLabel: "{\"ja_jp\": \"登録者\"}",
          fieldType: 99,
          fieldOrder: 16,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 194,
          fieldBelong: 6,
          fieldName: "activity_end_time",
          fieldLabel: "{\"ja_jp\": \"活動時間\"}",
          fieldType: 7,
          fieldOrder: 3,
          isDefault: true,
          maxLength: null,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 98,
          fieldBelong: 6,
          fieldName:  "updated_date",
          fieldLabel: "{\"ja_jp\": \"最終更新日\"}",
          fieldType: 7,
          fieldOrder: 17,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 195,
          fieldBelong: 6,
          fieldName: "activity_start_time",
          fieldLabel: "{\"ja_jp\": \"活動時間\"}",
          fieldType: 7,
          fieldOrder: 2,
          isDefault: true,
          maxLength: null,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 99,
          fieldBelong: 6,
          fieldName: "updated_user",
          fieldLabel: "{\"ja_jp\": \"最終更新者\"}",
          fieldType: 99,
          fieldOrder: 18,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 83,
          fieldBelong: 6,
          fieldName: "contact_date",
          fieldLabel: "{\"ja_jp\": \"接触日\"}",
          fieldType: 6,
          fieldOrder: 1,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 3,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 84,
          fieldBelong: 6,
          fieldName:  "activity_format_id",
          fieldLabel: "{\"ja_jp\": \"報告フォーマット\"}",
          fieldType: 99,
          fieldOrder: 7,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 3,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 85,
          fieldBelong: 6,
          fieldName: "activity_duration",
          fieldLabel: "{\"ja_jp\": \"活動時間\"}",
          fieldType: 8,
          fieldOrder: 4,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 3,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 86,
          fieldBelong: 6,
          fieldName: "employee_id",
          fieldLabel: "{\"ja_jp\": \"報告者\"}",
          fieldType: 99,
          fieldOrder: 6,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 87,
          fieldBelong: 6,
          fieldName: "interviewer",
          fieldLabel: "{\"ja_jp\": \"当日面談者\"}",
          fieldType: 99,
          fieldOrder: 9,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 88,
          fieldBelong: 6,
          fieldName: "customer_id",
          fieldLabel:  "{\"ja_jp\": \"顧客名\"}",
          fieldType: 99,
          fieldOrder: 8,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 89,
          fieldBelong: 6,
          fieldName: "customer_relation_id",
          fieldLabel:  "{\"ja_jp\": \"関係顧客\"}",
          fieldType: 99,
          fieldOrder: 10,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 90,
          fieldBelong: 6,
          fieldName: "next_schedule_id",
          fieldLabel: "{\"ja_jp\": \"次回スケジュール\"}",
          fieldType: 99,
          fieldOrder: 11,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 92,
          fieldBelong: 6,
          fieldName: "activity_target_id",
          fieldLabel:  "{\"ja_jp\": \"報告対象を選択\"}",
          fieldType: 99,
          fieldOrder: 5,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: true,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 94,
          fieldBelong: 6,
          fieldName: "product_trading_id",
          fieldLabel:  "{\"ja_jp\": \"取引商品\"}",
          fieldType: 99,
          fieldOrder: 13,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 95,
          fieldBelong: 6,
          fieldName: "memo",
          fieldLabel: "{\"ja_jp\": \"メモ\"}",
          fieldType: 10,
          fieldOrder: 14,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 0,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      }
  ],
  tabInfo: [
      {
          createdDate: "2020-05-27T16:59:12Z",
          createdUser: 1,
          updatedDate: "2020-05-27T16:59:12Z",
          updatedUser: 1,
          tabInfoId: 7,
          tabBelong: 6,
          tabId: 0,
          tabLabel: "{\"ja_jp\": \"基本情報\"}",
          tabOrder: 1,
          isDisplay: true,
          isDisplaySummary: true,
          maxRecord: 1
      },
      {
          createdDate: "2020-05-27T16:59:12Z",
          createdUser: 1,
          updatedDate: "2020-07-13T10:59:44.819740Z",
          updatedUser: 1,
          tabInfoId: 8,
          tabBelong: 6,
          tabId: 1,
          tabLabel: "{\"ja_jp\": \"基本情報\"}",
          tabOrder: 2,
          isDisplay: false,
          isDisplaySummary: false,
          maxRecord: 30
      },
      {
          createdDate: "2020-05-27T16:59:12Z",
          createdUser: 1,
          updatedDate: "2020-05-27T16:59:12Z",
          updatedUser: 1,
          tabInfoId: 9,
          tabBelong: 6,
          tabId: 2,
          tabLabel: "{\"ja_jp\": \"基本情報\"}",
          tabOrder: 3,
          isDisplay: true,
          isDisplaySummary: true,
          maxRecord: 30
      }
  ],
  fieldInfoProductTrading: [
      {
          fieldId: 170,
          fieldBelong: 16,
          fieldName: "product_trading_id",
          fieldLabel: "{\"ja_jp\": \"取引商品コード\"}",
          fieldType: 5,
          fieldOrder: 1,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 171,
          fieldBelong: 16,
          fieldName: "customer_id",
          fieldLabel: "{\"ja_jp\": \"顧客名\"}",
          fieldType: 99,
          fieldOrder: 2,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 172,
          fieldBelong: 16,
          fieldName: "product_id",
          fieldLabel: "{\"ja_jp\": \"商品名\"}",
          fieldType: 99,
          fieldOrder: 3,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 173,
          fieldBelong: 16,
          fieldName: "quantity",
          fieldLabel: "{\"ja_jp\": \"数量\"}",
          fieldType: 5,
          fieldOrder: 4,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 174,
          fieldBelong: 16,
          fieldName: "price",
          fieldLabel: "{\"ja_jp\": \"単価\"}",
          fieldType: 5,
          fieldOrder: 5,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: "円",
          typeUnit: 1,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 175,
          fieldBelong: 16,
          fieldName: "amount",
          fieldLabel: "{\"ja_jp\": \"金額\"}",
          fieldType: 5,
          fieldOrder: 6,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: "円",
          typeUnit: 1,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 176,
          fieldBelong: 16,
          fieldName: "product_trading_progress_id",
          fieldLabel:  "{\"ja_jp\": \"進捗状況\"}",
          fieldType: 99,
          fieldOrder: 7,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 177,
          fieldBelong: 16,
          fieldName: "order_plan_date",
          fieldLabel: "{\"ja_jp\": \"受注予定日\"}",
          fieldType: 6,
          fieldOrder: 8,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 178,
          fieldBelong: 16,
          fieldName: "end_plan_date",
          fieldLabel: "{\"ja_jp\": \"完了予定日\"}",
          fieldType: 6,
          fieldOrder: 9,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 179,
          fieldBelong: 16,
          fieldName:  "memo",
          fieldLabel:  "{\"ja_jp\": \"メモ\"}",
          fieldType: 10,
          fieldOrder: 10,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 180,
          fieldBelong: 16,
          fieldName:  "employee_id",
          fieldLabel:  "{\"ja_jp\": \"担当者\"}",
          fieldType: 99,
          fieldOrder: 11,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 1,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 181,
          fieldBelong: 16,
          fieldName: "created_date",
          fieldLabel: "{\"ja_jp\": \"登録日\"}",
          fieldType: 7,
          fieldOrder: 12,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 182,
          fieldBelong: 16,
          fieldName: "created_user",
          fieldLabel: "{\"ja_jp\": \"登録者\"}",
          fieldType: 99,
          fieldOrder: 13,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 183,
          fieldBelong: 16,
          fieldName:  "updated_date",
          fieldLabel: "{\"ja_jp\": \"最終更新日\"}",
          fieldType: 7,
          fieldOrder: 14,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      },
      {
          fieldId: 184,
          fieldBelong: 16,
          fieldName: "updated_user",
          fieldLabel: "{\"ja_jp\": \"最終更新者\"}",
          fieldType: 99,
          fieldOrder: 15,
          isDefault: true,
          maxLength: 0,
          modifyFlag: 0,
          availableFlag: 3,
          isDoubleColumn: false,
          ownPermissionLevel: null,
          othersPermissionLevel: null,
          defaultValue: null,
          currencyUnit: null,
          typeUnit: null,
          decimalPlace: null,
          urlType: null,
          urlTarget: null,
          urlText: null,
          linkTarget: null,
          iframeHeight: null,
          configValue: null,
          isLinkedGoogleMap: null,
          fieldGroup: null,
          lookupData: null,
          relationData: null,
          selectOrganizationData: null,
          tabData: [],
          lookupFieldId: null,
          fieldItems: [],
          differenceSetting: null
      }
  ],
  progresses: null,
  scenario: null
}
}