@startuml{組織追加画面.png}
title [組織追加画面]
hide footbox

actor ユーザー as user
boundary 組織追加画面 as view_1
boundary 組織一覧画面 as view_2
participant 組織API as api_organizations #cyan
participant プロジェクトAPI as api_projects #cyan

== 表示 ==
user -> view_1 :画面表示
activate view_1
    view_1 -> view_1 :画面描画
    view_1 --> user
deactivate view_1

== 組織追加 ==
user -> view_1 :組織追加
activate view_1
    view_1 -> view_1 :バリデーションチェック
    view_1 -> api_organizations : POST /organizations
    activate api_organizations
        api_organizations --> view_1 :201:作成した組織情報
    deactivate api_organizations
    view_1 -> view_2 :表示
deactivate view_1

@enduml
