@startuml{API_組織_組織別通知メール宛先削除.png}
title [組織_組織別通知メール宛先削除]
hide footbox

boundary 画面 as view
participant 組織API as api_organizations #cyan
database ユーザー所属 as table_affiliation <<dynamodb>> #royalblue
database 宛先 as table_destinations <<dynamodb>> #royalblue

view -> api_organizations : DELETE /organizations/{organization_id}/nofitymail/destinations
activate api_organizations
    api_organizations -> api_organizations :ユーザーID取得
    |||
    ref over api_organizations, table_affiliation :アクセス権限チェック
    |||
    api_organizations -> api_organizations :バリデーションチェック
    |||
    api_organizations -> api_organizations :宛先情報削除
    activate api_organizations
        api_organizations -> table_destinations :宛先レコード削除
        table_destinations --> api_organizations
        api_organizations --> api_organizations
    deactivate api_organizations
    |||
    api_organizations -> api_organizations :レスポンス作成
    api_organizations --> view :204
deactivate api_organizations

@enduml
