@startuml{API_組織_組織情報取得.png}
title [組織_組織情報取得]
hide footbox

boundary 画面 as view
participant 組織API as api_organizations #cyan
'database ユーザープール as user_pools <<cognito>> #purple
database ユーザー所属 as table_affiliation <<dynamodb>> #royalblue
database 組織 as table_organizations <<dynamodb>> #royalblue

view -> api_organizations : GET /organizations/{organization_id}
activate api_organizations
    api_organizations -> api_organizations :メールアドレス取得
    |||
    ref over api_organizations, table_affiliation :アクセス権限チェック
    |||
    api_organizations -> api_organizations :組織情報取得
    activate api_organizations
        api_organizations -> table_organizations :query
        table_organizations --> api_organizations
        api_organizations --> api_organizations
    deactivate api_organizations
    |||
    api_organizations -> api_organizations :レスポンス作成
    api_organizations --> view :200:組織情報
deactivate api_organizations

@enduml
