import { StyleSheet } from "react-native";
import { theme } from "../../../config/constants";

export const shareStyles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    height: 45,
    alignItems: "center",
    flexDirection: "row",
    borderBottomColor: theme.colors.gray200,
    borderBottomWidth: 1,
    justifyContent: "center",
  },
  iconRight: { position: "absolute", right: theme.space[1] },
  iconClose: { position: "absolute", left: theme.space[3] },
  hitSlop: { top: 10, right: 10, left: 10, bottom: 10 },
  txtHeader: {
    fontSize: 18,
  },
  boxGroup: {
    borderColor: theme.colors.gray,
    borderRadius: theme.borRadius.borderRadius15,
    borderWidth: 1,
    flexDirection: "row",
    minWidth: "40%",
    alignSelf: "flex-start",
    margin: theme.space[2],
    alignItems: "center",
    justifyContent: "center",
    padding: theme.space[1],
    zIndex: 6,
    position: "relative",
  },
  txtGroup: {
    fontSize: theme.fontSizes[1],
    paddingLeft: theme.space[3],
    paddingRight: theme.space[5],
    color: theme.colors.gray1,
  },
  spaceBottom: {},
  lineView: {
    height: 1,
    marginHorizontal: theme.space[3],
    backgroundColor: theme.colors.gray100,
  },
  txtBlack12: {
    fontSize: theme.fontSizes[1],
    padding: theme.space[1],
  },
  txtGray12: {
    fontSize: theme.fontSizes[1],
    padding: theme.space[1],
    color: theme.colors.gray300,
  },
  textInput: {
    alignSelf: "flex-start",
    maxHeight: 300,
    width: "90%",
    paddingBottom: theme.space[2],
    marginHorizontal: theme.space[3],
  },
  bottomView: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  shareView: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    margin: theme.space[4],
    borderRadius: theme.borderRadius,
    borderWidth: 1,
    paddingVertical: theme.space[3],
    borderColor: theme.colors.gray200,
  },
  itemShareViewLeft: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: theme.space[1],
  },
  lineVerticalView: {
    marginTop: theme.space[1],
    width: 4,
    flex: 1,
    backgroundColor: theme.colors.gray200,
  },
  contentShareView: { flex: 9, paddingRight: theme.space[2] },
  boxEmployeeInfo: {
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    // zIndex: 99,
  },
  avatar: {
    width: 24,
    height: 24,
    resizeMode: "contain",
  },
  txtBlue: {
    padding: theme.space[1],
    color: theme.colors.blue200,
  },
  boxListShare: {
    flexDirection: "row",
    marginHorizontal: theme.space[3],
    paddingVertical: theme.space[2],
    borderBottomColor: theme.colors.gray200,
    borderTopColor: theme.colors.gray200,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    alignItems: "center",
    zIndex: 1,
  },
  smallIcon: {
    width: 12,
    height: 12,
    resizeMode: "contain",
  },
  boxSendName: {
    borderRadius: theme.borRadius.borderRadius10,
    backgroundColor: theme.colors.gray1,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingHorizontal: theme.space[2],
    paddingVertical: theme.space[1],
    marginHorizontal: theme.space[2],
  },
  txtWhite: {
    padding: theme.space[1],
    color: theme.colors.white,
    fontSize: theme.fontSizes[1],
  },
  btnComplete: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    paddingHorizontal: theme.space[5],
    paddingVertical: theme.space[2],
    margin: theme.space[2],
    borderRadius: theme.borderRadius,
    backgroundColor: theme.colors.blue200,
  },
  btnInComplete: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    paddingHorizontal: theme.space[5],
    paddingVertical: theme.space[2],
    margin: theme.space[2],
    borderRadius: theme.borderRadius,
    backgroundColor: theme.colors.gray100,
  },
  boxIcon: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: theme.space[2],
  },
  icon: {
    height: 24,
    resizeMode: "contain",
    marginHorizontal: theme.space[2],
  },
  iconFile: {
    height: 17,
    resizeMode: "contain",
    marginHorizontal: theme.space[2],
  },
  boxSend: {
    alignItems: "center",
    flexDirection: "row",
    borderTopColor: theme.colors.gray200,
    borderTopWidth: 1,
    justifyContent: "space-between",
  },
  suggestView: {
    maxHeight: 250,
    // zIndex: 10,
  },
  itemSuggestView: {
    alignItems: "center",
    flexDirection: "row",
    borderBottomColor: theme.colors.gray200,
    borderBottomWidth: 1,
    paddingHorizontal: theme.space[1],
    paddingVertical: theme.space[3],
    marginHorizontal: theme.space[3],
  },
  boxShareFile: {
    marginHorizontal: theme.space[4],
    flexDirection: "row",
    backgroundColor: theme.colors.gray3,
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: theme.space[1],
    padding: theme.space[2],
    borderRadius: theme.borRadius.borderRadius12,
  },
  boxListGroup: {
    position: "absolute",
    top: 35,
    height: 150,
    left: theme.space[2],
    width: "80%",
    backgroundColor: theme.colors.white,
    borderRadius: theme.borRadius.borderRadius12,
    borderColor: theme.colors.gray200,
    borderWidth: 1,
    zIndex: 90,
    shadowColor: theme.colors.gray200,
    shadowOffset: {
      width: 3,
      height: 12,
    },
    shadowOpacity: 1,
    shadowRadius: 16.0,
    paddingVertical: theme.space[1],
    elevation: 24,
  },
  circleGroupName: {
    width: 24,
    height: 24,
    borderRadius: 12,
    resizeMode: "cover",
    padding: theme.space[1],
    margin: theme.space[2],
    alignItems: "center",
    borderWidth: 2,
    borderColor: theme.colors.gray200,
    justifyContent: "center",
  },
  spaceView: { height: 200 },
  groupSelectedView: {
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    backgroundColor: theme.colors.blue,
  },
});
