export const Images = {
  schedule: {
    ic_up: require('../assets/images/Schedule/ic-up.png'),
    ic_down: require('../assets/images/Schedule/ic-down.png'),
    ic_go_out: require('../assets/images/Schedule/ic-goout.png'),
    ic_flag_green: require('../assets/images/Schedule/ic-flag-green.png'),
    ic_flag_red: require('../assets/images/Schedule/ic-flag-red.png'),
    ic_flag_completed: require('../assets/images/Schedule/ic-flag-completed.png'),
    ic_type_task: require('../assets/images/Schedule/ic-type-task.png'),
    ic_type_task_complete: require('../assets/images/Schedule/ic-type-task-complete.png'),
    ic_type_task_expired: require('../assets/images/Schedule/ic-type-task-expired.png'),
    ic_close: require('../assets/images/Schedule/ic-close.png'),
    ic_triangle: require('../assets/images/Schedule/ic-triangle.png'),
    ic_ellipse: require('../assets/images/Schedule/ic-ellipse.png'),
    ic_ellipse_no_border: require('../assets/images/Schedule/ic-ellipse-no-border.png'),
    ic_task: require('../assets/images/Schedule/ic-task.png'),
    ic_chart_up: require('../assets/images/Schedule/ic-chart-up.png'),
    loading: require('../assets/images/icon_common/loading.gif'),
    loading_24: require('../assets/images/icon_common/loading_24px.gif'),
    no_data: require('../assets/images/icon_common/no_data.png'),
  },
  schedule_type: {
    ic_calendar_phone: require('../assets/images/110212_LocalNavigation/icon_phone.png'),
    icon_person_red: require('../assets/images/110212_LocalNavigation/icon_person_red.png'),
    icon_group_user: require('../assets/images/110212_LocalNavigation/icon_group_user.png'),
    icon_chart: require('../assets/images/110212_LocalNavigation/icon_chart.png'),
    icon_user1: require('../assets/images/scheduleType/type-2.png'),
    icon_text : require('../assets/images/scheduleType/type-7.png'),
    icon_bag :  require('../assets/images/scheduleType/type-4.png'),
    icon_bell:  require('../assets/images/scheduleType/type-6.png')
  },
  schedule_details: {
    icon_close: require('../assets/images/icon_common/ic_close.png'),
    icon_check: require('../assets/images/icon_common/icon_check.png'),
    icon_share: require('../assets/images/icon_common/icon_share.png'),
    icon_save: require('../assets/images/icon_common/icon_save.png'),
    icon_pencil: require('../assets/images/icon_common/icon_pencil.png'),
    icon_recycle_bin: require('../assets/images/icon_common/icon_recycle_bin.png'),
    icon_building: require('../assets/images/icon_common/icon_building.png'),
    icon_location: require('../assets/images/icon_common/icon_location.png'),
    icon_door: require('../assets/images/icon_common/icon_door_open.png'),
    icon_user: require('../assets/images/icon_common/icon_user.png'),
    icon_user_blue: require('../assets/images/icon_common/icon_user_blue.png'),
    icon_user_green: require('../assets/images/icon_common/icon_user_green.png'),
    icon_user_girl: require('../assets/images/icon_common/icon_user_girl.png'),
    icon_card_visit: require('../assets/images/icon_common/icon_card_visit.png'),
    icon_flag: require('../assets/images/icon_common/icon_flag.png'),
    icon_tag_file: require('../assets/images/icon_common/icon_tag_file.png'),
    emotion_smile: require('../assets/images/icon_common/emotion_smile.png'),
    emotion_cry: require('../assets/images/icon_common/emotion_cry.png'),
    emotion_smile_1: require('../assets/images/icon_common/emotion_smile_1.png'),
    icon_check_short: require('../assets/images/icon_common/icon_check_short.png'),
    icon_timeline: require('../assets/images/icon_common/icon_timeline.png'),
  },
  box_comment: {
    icon_comment: require("../assets/images/icon_common/icon_comment.png"),
    icon_double_comma: require("../assets/images/icon_common/icon_double_comma.png"),
    icon_smile: require("../assets/images/icon_common/icon_smile.png"),
    icon_star: require("../assets/images/icon_common/icon_star.png"),
  },
  scheduleRegistration: {
    ic_check: require("../assets/images/ScheduleRegistration/ic_check.png"),
    ic_close: require("../assets/images/ScheduleRegistration/ic_close.png"),
  },

  globalToolSchedule: {
    ic_pre: require("../assets/images/110211_GlobalToolSchedule/icon_pre.png"),
    ic_next: require("../assets/images/110211_GlobalToolSchedule/icon_next.png"),
    ic_person_red: require("../assets/images/110211_GlobalToolSchedule/icon_person_red.png"),
    ic_building: require("../assets/images/110211_GlobalToolSchedule/icon_building.png"),
    ic_location: require("../assets/images/110211_GlobalToolSchedule/icon_location.png"),
    ic_user: require("../assets/images/110211_GlobalToolSchedule/icon_user.png"),
    ic_check:require("../assets/images/110211_GlobalToolSchedule/icon_check.png"),
    ic_close:require("../assets/images/110211_GlobalToolSchedule/ic_close.png"),
    ic_share:require("../assets/images/110211_GlobalToolSchedule/icon_share.png"),
    ic_down:require("../assets/images/110211_GlobalToolSchedule/icon_down.png"),
    ic_up:require("../assets/images/110211_GlobalToolSchedule/icon_up.png"),
    ic_sort: require("../assets/images/110211_GlobalToolSchedule/ic_sort.png"),
  },

  localNavigation:{
    ic_down:require("../assets/images/110212_LocalNavigation/icon_down.png"),
    ic_up:require("../assets/images/110212_LocalNavigation/icon_up.png"),
    ic_person_red: require("../assets/images/110212_LocalNavigation/icon_person_red.png"),
    ic_bag: require("../assets/images/110212_LocalNavigation/icon_bag.png"),
    ic_chair: require("../assets/images/110212_LocalNavigation/icon_chair.png"),
    ic_checklist: require("../assets/images/110212_LocalNavigation/icon_checklist.png"),
    ic_close: require("../assets/images/110212_LocalNavigation/icon_close.png"),
    ic_check: require("../assets/images/110212_LocalNavigation/icon_check.png"),
    ic_flag: require("../assets/images/110212_LocalNavigation/icon_flag.png"),
    ic_group_user: require("../assets/images/110212_LocalNavigation/icon_group_user.png"),
    ic_phone: require("../assets/images/110212_LocalNavigation/icon_phone.png"),
    ic_text: require("../assets/images/110212_LocalNavigation/icon_text.png"),
    ic_chart: require("../assets/images/110212_LocalNavigation/icon_chart.png"),
    ic_next: require("../assets/images/110212_LocalNavigation/icon_next.png"),
  },
  listActivity:{
    ic_down:require("../assets/images/ActivityList/icon_down.png"),
    ic_cmt:require("../assets/images/ActivityList/icon_comment.png"),
    ic_detail:require("../assets/images/ActivityList/icon_detail.png"),
    ic_notify:require("../assets/images/ActivityList/icon_notify.png"),
    ic_quote:require("../assets/images/ActivityList/icon_quote.png"),
    ic_remove:require("../assets/images/ActivityList/icon_remove.png"),
    ic_run:require("../assets/images/ActivityList/icon_run.png"),
    ic_share:require("../assets/images/ActivityList/icon_share.png"),
    ic_smile:require("../assets/images/ActivityList/icon_smile.png"),
    ic_star:require("../assets/images/ActivityList/icon_star.png"),
    ic_user:require("../assets/images/ActivityList/icon_user.png"),
    iconUserSmall:require("../assets/images/ActivityList/icon_user_small.png"),
    ic_search:require("../assets/images/ActivityList/icon-search.png"),
    ic_search_ad:require("../assets/images/ActivityList/icon-search_ad.png"),
    ic_close:require("../assets/images/ActivityList/icon_close.png"),
    ic_pen:require("../assets/images/ActivityList/icon_pen.png"),
    ic_timeLine:require("../../../../assets/icons/timeline.png"),
    ic_activityHistories:require("../../../../assets/icons/ic_check_list_clock.png"),
    ic_check: require("../assets/images/110212_LocalNavigation/icon_check.png"),
    ic_next: require("../assets/images/110212_LocalNavigation/icon_next.png"),
  }
};
