export const FIELD_INFO_BASIC = {
  fieldInfo: [
    {
      fieldId: 128,
      fieldBelong: 4,
      fieldName: "business_card_id",
      fieldLabel: '{"ja_jp": "名刺コード"}',
      fieldType: 9,
      fieldOrder: 1,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "10001",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 129,
      fieldBelong: 4,
      fieldName: "business_card_image_name",
      fieldLabel: '{"ja_jp": "名刺画像"}',
      fieldType: 99,
      fieldOrder: 2,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "サンプル株式会社",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 130,
      fieldBelong: 4,
      fieldName: "customer_name",
      fieldLabel: '{"ja_jp": "顧客名"}',
      fieldType: 99,
      fieldOrder: 3,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "meishi.jpg",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 131,
      fieldBelong: 4,
      fieldName: "business_card_name",
      fieldLabel: '{"ja_jp": "顧客名"}',
      fieldType: 9,
      fieldOrder: 4,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "サンプル株式会社",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 132,
      fieldBelong: 4,
      fieldName: "business_card_name",
      fieldLabel: '{"ja_jp": "名刺氏名"}',
      fieldType: 9,
      fieldOrder: 5,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "名刺 太郎",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 133,
      fieldBelong: 4,
      fieldName: "business_card_name_kana",
      fieldLabel: '{"ja_jp": "名刺氏名（かな）"}',
      fieldType: 9,
      fieldOrder: 6,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "めいしたろう",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 134,
      fieldBelong: 4,
      fieldName: "department_name",
      fieldLabel: '{"ja_jp": "部署・役職"}',
      fieldType: 9,
      fieldOrder: 7,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "代表取締役",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 135,
      fieldBelong: 4,
      fieldName: "department_name",
      fieldLabel: '{"ja_jp": "部署・役職"}',
      fieldType: 9,
      fieldOrder: 8,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "代表取締役",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 136,
      fieldBelong: 4,
      fieldName: "adress_name",
      fieldLabel: '{"ja_jp": "住所"}',
      fieldType: 99,
      fieldOrder: 9,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "〒000-0000 東京都杉並区荻窪1-1-1 荻窪第一ビル 11F",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 137,
      fieldBelong: 4,
      fieldName: "email_address",
      fieldLabel: '{"ja_jp": "メールアドレス"}',
      fieldType: 99,
      fieldOrder: 10,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "sample@sample.com",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 138,
      fieldBelong: 4,
      fieldName: "phone_number",
      fieldLabel: '{"ja_jp": "電話番号"}',
      fieldType: 99,
      fieldOrder: 11,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "03-3333-3333",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 139,
      fieldBelong: 4,
      fieldName: "cell_phone_number",
      fieldLabel: '{"ja_jp": "携帯番号"}',
      fieldType: 99,
      fieldOrder: 12,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "090-1234-5678",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 140,
      fieldBelong: 4,
      fieldName: "receiver_name",
      fieldLabel: '{"ja_jp": "受取人"}',
      fieldType: 9,
      fieldOrder: 13,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "受取太郎\n受取日：2019/12/12　最終接触日:2019/12/12",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 141,
      fieldBelong: 4,
      fieldName: "last_contact_date",
      fieldLabel: '{"ja_jp": "最終接触日"}',
      fieldType: 99,
      fieldOrder: 14,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "2019/10/10",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 142,
      fieldBelong: 4,
      fieldName: "last_contact_date",
      fieldLabel: '{"ja_jp": "最終接触日"}',
      fieldType: 9,
      fieldOrder: 15,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "2019/10/10",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 143,
      fieldBelong: 4,
      fieldName: "employment_flag",
      fieldLabel: '{"ja_jp": "在職フラグ"}',
      fieldType: 9,
      fieldOrder: 16,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "在職中",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 144,
      fieldBelong: 4,
      fieldName: "campaign_name",
      fieldLabel: '{"ja_jp": "キャンペーン"}',
      fieldType: 9,
      fieldOrder: 17,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "キャンペーンA",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 145,
      fieldBelong: 4,
      fieldName: "memo",
      fieldLabel: '{"ja_jp": "メモ"}',
      fieldType: 9,
      fieldOrder: 18,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "メモが入ります。",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 146,
      fieldBelong: 4,
      fieldName: "created_date",
      fieldLabel: '{"ja_jp": "登録日"}',
      fieldType: 9,
      fieldOrder: 19,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "2019/10/10",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 147,
      fieldBelong: 4,
      fieldName: "created_person",
      fieldLabel: '{"ja_jp": "登録者"}',
      fieldType: 99,
      fieldOrder: 20,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "社員A",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 148,
      fieldBelong: 4,
      fieldName: "updated_date",
      fieldLabel: '{"ja_jp": "最終更新日"}',
      fieldType: 9,
      fieldOrder: 21,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "2019/10/10",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
    {
      fieldId: 149,
      fieldBelong: 4,
      fieldName: "updated_person",
      fieldLabel: '{"ja_jp": "最終更新者"}',
      fieldType: 99,
      fieldOrder: 22,
      isDefault: true,
      maxLength: 0,
      modifyFlag: 0,
      availableFlag: 3,
      isDoubleColumn: true,
      ownPermissionLevel: null,
      othersPermissionLevel: null,
      defaultValue: "社員A",
      currencyUnit: "",
      typeUnit: 0,
      decimalPlace: 0,
      urlType: 0,
      urlTarget: "",
      urlEncode: 0,
      urlText: "",
      linkTarget: null,
      configValue: "",
      isLinkedGoogleMap: false,
      fieldGroup: 0,
      lookupData: {
        extensionBelong: 0,
        searchKey: 0,
        itemReflect: [],
      },
      relationData: {
        extensionBelong: 0,
        fieldId: 0,
        format: 0,
        displayFieldId: 0,
        displayTab: 0,
        displayFields: null,
      },
      tabData: [],
      updatedDate: "2020-06-01T02:51:18.528859Z",
      fieldItems: [],
    },
  ],
};

export const PRODUCT_TRADING_BUSINESS_CARD = {
  listProductDummy: [
    {
      productTradingId: 1,
      customerId: 1,
      productTradingProgressId: 1,
      progressName: "finish",
      progressOrder: 1,
      isAvailable: true,
      productId: 1,
      productName: "社員A",
      quantity: 1,
      price: 3000,
      amount: 1000,
      customerName: "社員A",
      employeeId: 1,
      employeeName: "",
      endPlanDate: "2020/12/12",
      orderPlanDate: "2020/12/12",
      memo: "ABC",
      updateDate: "2020/12/12",
      productTradingData: [
        { fieldType: 10, key: "text1", value: "Hello word" },
        { fieldType: 10, key: "text1", value: "Hello word" },
      ],
    },
    {
      productTradingId: 2,
      customerId: 1,
      productTradingProgressId: 1,
      progressName: "finish",
      progressOrder: 1,
      isAvailable: true,
      productId: 1,
      productName: "社員A",
      quantity: 1,
      price: 3000,
      amount: 1000,
      customerName: "社員A",
      employeeId: 1,
      employeeName: "社員A",
      endPlanDate: "2020/12/12",
      orderPlanDate: "2020/12/12",
      memo: "ABC",
      updateDate: "2020/12/12",
      productTradingData: [
        { fieldType: 10, key: "text1", value: "Hello word" },
        { fieldType: 10, key: "text1", value: "Hello word" },
      ],
    },
    {
      productTradingId: 3,
      customerId: 1,
      productTradingProgressId: 1,
      progressName: "finish",
      progressOrder: 1,
      isAvailable: true,
      productId: 1,
      productName: "社員A",
      quantity: 1,
      price: 3000,
      amount: 1000,
      customerName: "社員A",
      employeeId: 1,
      employeeName: "社員A",
      endPlanDate: "2020/12/12",
      orderPlanDate: "2020/12/12",
      memo: "ABC",
      updateDate: "2020/12/12",
      productTradingData: [
        { fieldType: 10, key: "text1", value: "Hello word" },
        { fieldType: 10, key: "text1", value: "Hello word" },
      ],
    },
    {
      productTradingId: 4,
      customerId: 1,
      productTradingProgressId: 1,
      progressName: "finish",
      progressOrder: 1,
      isAvailable: true,
      productId: 1,
      productName: "A",
      quantity: 1,
      price: 3000,
      amount: 1000,
      customerName: "社員A",
      employeeId: 1,
      employeeName: "社員A",
      endPlanDate: "2020/12/12",
      orderPlanDate: "2020/12/12",
      memo: "ABC",
      updateDate: "2020/12/12",
      productTradingData: [
        { fieldType: 10, key: "text1", value: "Hello word" },
        { fieldType: 10, key: "text1", value: "Hello word" },
      ],
    },
    {
      productTradingId: 5,
      customerId: 1,
      productTradingProgressId: 1,
      progressName: "finish",
      progressOrder: 1,
      isAvailable: true,
      productId: 1,
      productName: "社員A",
      quantity: 1,
      price: 3000,
      amount: 1000,
      customerName: "社員A",
      employeeId: 1,
      employeeName: "社員A",
      endPlanDate: "2020/12/12",
      orderPlanDate: "2020/12/12",
      memo: "ABC",
      updateDate: "2020/12/12",
      productTradingData: [
        { fieldType: 10, key: "text1", value: "Hello word" },
        { fieldType: 10, key: "text1", value: "Hello word" },
      ],
    },
    {
      productTradingId: 6,
      customerId: 1,
      productTradingProgressId: 1,
      progressName: "finish",
      progressOrder: 1,
      isAvailable: true,
      productId: 1,
      productName: "社員A",
      quantity: 1,
      price: 3000,
      amount: 1000,
      customerName: "社員A",
      employeeId: 1,
      employeeName: "社員A",
      endPlanDate: "2020/12/12",
      orderPlanDate: "2020/12/12",
      memo: "ABC",
      updateDate: "2020/12/12",
      productTradingData: [
        { fieldType: 10, key: "text1", value: "Hello word" },
        { fieldType: 10, key: "text1", value: "Hello word" },
      ],
    },
  ],
};
