import { StyleSheet } from "react-native";
import { theme } from "../../../../config/constants";

export const activityHistoryStyle = StyleSheet.create({
  container: {
    flex: 1,
  },
  avatar: {
    resizeMode: "cover",
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: theme.space[2],
  },
  smallAvatar: {
    resizeMode: "cover",
    width: 24,
    height: 24,
    borderRadius: 12,
    marginHorizontal: theme.space[2],
  },
  boxIconUpdate: {
    flexDirection: "row",
    position: "absolute",
    right: -5,
    top: 20,
    alignItems: "center",
  },
  boxProductName: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  boxTxtPrice: {
    justifyContent: "space-between",
    alignItems: "stretch",
  },
  boxTxtActivityInfo: {
    width: "85%",
  },
  boxProductInfo: {
    flex: 2,
    paddingRight: theme.space[6],
  },
  boxHeaderLeft: {
    flex: 4,
  },
  boxHeaderRight: {
    flex: 1,
    // justifyContent: "space-between",
  },
  icon: {
    resizeMode: "contain",
    width: 16,
    height: 16,
    marginHorizontal: theme.space[1],
  },
  iconSmall: {
    resizeMode: "cover",
    width: 12,
    height: 12,
    marginHorizontal: theme.space[1],
  },
  containerList: {
    flex: 1,
    backgroundColor: "white",
  },

  txtBlueBold: {
    fontWeight: "bold",
    fontSize: theme.fontSizes[1],
    color: theme.colors.blue200,
    marginRight: theme.space[1],
  },
  txtSize10Blue: {
    fontSize: theme.fontSizes[0],
    color: theme.colors.blue200,
    marginRight: theme.space[1],
  },
  txtSize12Blue: {
    fontSize: theme.fontSizes[1],
    color: theme.colors.blue200,
    marginRight: theme.space[1],
  },
  txtSize12Red: {
    fontSize: theme.fontSizes[1],
    color: theme.colors.red,
    marginRight: theme.space[1],
  },
  txtSize12Sky: {
    fontSize: theme.fontSizes[1],
    color: theme.colors.blue200,
    marginRight: theme.space[1],
  },
  txtSize12Green: {
    fontSize: theme.fontSizes[1],
    color: "green",
    marginRight: theme.space[1],
  },
  txtSize10: {
    fontSize: theme.fontSizes[0],
    marginRight: theme.space[1],
  },
  txtSize12: {
    fontSize: theme.fontSizes[1],
    marginRight: theme.space[1],
  },
  txtSize12Bold: {
    fontSize: theme.fontSizes[1],
    fontWeight: "bold",
    marginRight: theme.space[1],
  },
  txtTimeLength: {
    flex: 1,
  },
  button: {
    height: 30,
    backgroundColor: theme.colors.gray200,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: theme.space[3],
  },
  boxHistory: {
    borderColor: theme.colors.gray200,
    borderWidth: 1,
    margin: 10,
  },
  boxHorizontal: {
    flexDirection: "row",
    paddingTop: theme.space[2],
    flex: 1,
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  boxTimeLine: {
    flexDirection: "row",
    paddingVertical: theme.space[2],
    flex: 1,
    justifyContent: "space-evenly",
    alignItems: "center",
    borderTopWidth: 1,
    marginTop: theme.space[2],
    borderTopColor: theme.colors.gray200,
  },
  boxHorizontal2: {
    flexDirection: "row",
    alignItems: "center",
  },
  spaceBottom: {
    paddingBottom: 4,
  },
  boxHorizontal3: {
    flexDirection: "row",
    paddingVertical: theme.space[2],
    paddingHorizontal: theme.space[4],
    justifyContent: "space-between",
    alignItems: "center",
  },
  containerContent: {
    paddingHorizontal: theme.space[4],
  },
});

export const itemTabStyles = StyleSheet.create({
  container: {
    backgroundColor: "white",
    height: 30,
    flexDirection: "row",
    marginLeft: 30,
    // justifyContent: "space-between",
  },
  boxTab: {
    flexDirection: "row",
    justifyContent: "flex-start",
    flex: 1,
    alignItems: "center",
    paddingTop: 0,
    marginTop: 0,
    backgroundColor: "transparent",
    marginLeft: -30,
  },
  borderBottom: {
    borderBottomWidth: 2,
    borderBottomColor: theme.colors.gray100,
    zIndex: 49,
    bottom: 0,
    position: "absolute",
  },
  titleTab: {
    position: "absolute",
    zIndex: 50,
    alignItems: "center",
    right: "20%",
    width: "60%",
    // backgroundColor: "red",
  },
  solidView: {
    height: 1,
    width: "80%",
    backgroundColor: theme.colors.blue200,
    zIndex: 50,
    bottom: 0,
    position: "absolute",
  },
  rectangleView: {
    width: "70%",
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
    height: 31,
    borderColor: "black",
    zIndex: 2,
  },
  rectangleViewLast: {
    width: "78%",
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
    height: 31,
    borderColor: "black",
    zIndex: 2,
  },
  rectangleViewFirst: {
    width: "68%",
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
    height: 31,
    borderColor: "black",
    zIndex: 2,
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    // borderTopColor: theme.colors.blue200,
    // borderTopWidth: 2,
    // borderBottomWidth: 2,
  },
  triangleView: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 16,
    borderRightWidth: 16,
    borderBottomWidth: 16,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    transform: [{ rotate: "90deg" }],
    margin: 0,
    marginLeft: -8,
    borderWidth: 0,
    zIndex: 2,
  },

  borderTriangle: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 17,
    borderRightWidth: 17,
    borderBottomWidth: 17,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "white",
    transform: [{ rotate: "90deg" }],
    margin: 0,
    zIndex: 1,
    marginLeft: -32,
    borderWidth: 0,
  },
  lastView: {
    zIndex: 5,
    position: "absolute",
    width: "20%",
    height: 30,
    right: 0,
    borderBottomColor: theme.colors.gray100,
    borderBottomWidth: 2,
    borderTopWidth: 2,
    borderTopColor: theme.colors.gray100,
  },
});

export const itemProductTabStyles = StyleSheet.create({
  container: {
    backgroundColor: "white",
    height: 30,
    flexDirection: "row",
    marginLeft: 30,
    // justifyContent: "space-between",
  },
  boxTab: {
    flexDirection: "row",
    justifyContent: "flex-start",
    flex: 1,
    alignItems: "center",
    paddingTop: 0,
    marginTop: 0,
    backgroundColor: "transparent",
    marginLeft: -30,
  },
  borderBottom: {
    borderBottomWidth: 2,
    borderBottomColor: theme.colors.gray100,
    zIndex: 49,
    bottom: 0,
    position: "absolute",
  },
  titleTab: {
    position: "absolute",
    zIndex: 50,
    alignItems: "center",
    right: "20%",
    width: "60%",
    // backgroundColor: "red",
  },
  solidView: {
    height: 1,
    width: "80%",
    backgroundColor: theme.colors.blue200,
    zIndex: 50,
    bottom: 0,
    position: "absolute",
  },
  rectangleView: {
    width: "70%",
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
    height: 31,
    borderColor: "black",
    zIndex: 2,
  },
  rectangleViewLast: {
    width: "90%",
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
    height: 31,
    borderColor: "black",
    zIndex: 2,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
  },
  rectangleViewFirst: {
    width: "70%",
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
    height: 31,
    borderColor: "black",
    zIndex: 2,
  },
  triangleView: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 16,
    borderRightWidth: 16,
    borderBottomWidth: 16,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    transform: [{ rotate: "90deg" }],
    margin: 0,
    marginLeft: -8,
    borderWidth: 0,
    zIndex: 2,
  },
  triangleViewFirst: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 16,
    borderRightWidth: 16,
    borderBottomWidth: 16,
    borderLeftColor: "transparent",
    borderBottomColor: "white",
    borderRightColor: "transparent",
    transform: [{ rotate: "90deg" }],
    margin: 0,
    borderWidth: 0,
    position: "absolute",
    left: "-13%",
    zIndex: 2,
  },
  borderTriangle: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 17,
    borderRightWidth: 17,
    borderBottomWidth: 17,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "white",
    transform: [{ rotate: "90deg" }],
    margin: 0,
    zIndex: 1,
    marginLeft: -32,
    borderWidth: 0,
  },
  lastView: {
    zIndex: 5,
    position: "absolute",
    width: "20%",
    height: 30,
    right: 0,
    borderBottomColor: theme.colors.gray100,
    borderBottomWidth: 2,
    borderTopWidth: 2,
    borderTopColor: theme.colors.gray100,
  },
});
