@startuml{API_チェック_セキュリティチェック結果レポートファイルURL取得.png}
title [チェックAPI_セキュリティチェック結果レポートファイルURL取得]
hide footbox

boundary 画面 as view
participant チェックAPI as api_check #cyan
database ユーザー所属 as table_affiliation <<dynamodb>> #royalblue
database チェック履歴 as table_check_history <<dynamodb>> #royalblue
'database レポートストレージ as storage <<s3>> #crimson

view -> api_check :GET /check/securitycheck/results/{history_id}/output
activate api_check
    api_check -> api_check :メールアドレス取得
    |||
    api_check -> table_check_history :チェック履歴情報取得
    table_check_history --> api_check
    api_check -> api_check :チェック履歴情報から組織IDを取得
    |||
    ref over api_check, table_affiliation :アクセス権限チェック
    |||
    api_check -> api_check :署名付きURLを作成
    api_check -> api_check :レスポンス作成
    api_check --> view :200:ダウンロードURL
deactivate api_check

@enduml
