export const TAB_ID = {
  BASIC_INFORMATION: 0,
  CHANGE_HISTORY: 2,
  CALENDAR: 9,
  PARTICIPATING_GROUP: 7,
  TRADING_PRODUCT: 1,
  PROSPECT: 8,
  EMAIL: 6,
  TASK: 5,
  BUSINESS_CARD: 3,
  CUSTOMER: 4
}